LABEL : ADD-CAULDRON
DELAY : 100
Keyboard : F12 : KeyDown
DELAY : 120
Keyboard : F12 : KeyUp
DELAY : 400
LABEL : WAIT-NAG3
IF IMAGE : Qk3+AwAAAAAAADYAAAAoAAAAFgAAAAsAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAACBgp/wgYKf8IGCn/CBgp/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wAQIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wAQIf8AECH/CBgh/wgYIf8IGCH/CBgh/wgYIf8AAAD/AAAA/wAAAP8AAAD/CBgh/wgYIf8AAAD/CBgh/wgYIf8AECH/CBgh/wgYIf8AAAD/AAAA/wgYIf8AAAD/ABAh/wAAAP8AECH/CBgh/wgYIf8A/wD/AP8A/wD/AP8A/wD/AAAA/wgYIf8A/wD/AAAA/wgYKf8IGCn/CBgh/wgYIf8A/wD/AP8A/wgYIf8A/wD/AAAA/wD/AP8AAAD/CBgh/wgYIf8A/wD/ECEp/wAAAP8AAAD/AP8A/wAAAP8QISn/AP8A/wAAAP8QISn/ECEp/wgYKf8A/wD/AAAA/wgYIf8AECH/AP8A/wAAAP8A/wD/AAAA/wgYIf8IGCH/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAD/CBgp/wD/AP8AAAD/CBgp/xAhKf8IGCn/AP8A/wAAAP8IGCH/ABAh/wD/AP8AAAD/AP8A/wAAAP8IGCn/ECEp/wD/AP8IGCH/AAAA/wAAAP8A/wD/CBgh/wgYIf8A/wD/AAAA/wAAAP8AAAD/CBgh/wD/AP8AAAD/AAAA/wAAAP8A/wD/AAAA/wD/AP8AAAD/AAAA/wAAAP8A/wD/AP8A/wD/AP8A/wD/ECEp/wgYIf8A/wD/AP8A/wD/AP8A/wD/CBgh/wD/AP8A/wD/AP8A/wD/AP8IGCH/AP8A/wgYIf8A/wD/AP8A/wD/AP8A/wD/CBgh/wgYKf8IGCn/CBgp/xAhKf8IGCn/CBgh/wD/AP8AAAD/CBgp/wgYIf8IGCH/AP8A/wAAAP8AECH/CBgh/wgYIf8AAAD/CBgh/xAhKf8QISn/ECEp/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wAQGP8A/wD/CBgh/wAAAP8AAAD/CBgh/wD/AP8AEBj/CBgh/wgYIf8A/wD/CBgh/wgYIf8IGCn/ECEp/wgYKf8IGCH/ABAh/wAQIf8AEBj/ABAY/wAQIf8AEBj/ABAh/wD/AP8A/wD/CBgh/wgYIf8IGCH/CBgh/wAQIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYKf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8QISn/CBgh/wAQGP8AEBj/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYKf8IGCH/CBgh/wgYIf8= : 0 : 40 : 0 : 370;376;500;120
DELAY : 4000
GOTO : WAIT-NAG3
ENDIF
FIND IMAGE : Qk0uAgAAAAAAADYAAAAoAAAABwAAABIAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/wgYGP8QKTH/EDk5/xhCSv8YSlL/EEJC/yExMf8hQkr/GEpS/xA5Qv8QMTn/GDlC/xA5Qv8hMTH/GDE5/xg5Of8YOTn/GDk5/xgxOf8YMTn/ISEp/yEpMf8hKTH/ISkx/yEpMf8hKTH/ITEx/yEpKf8hKSn/KSEp/ykpMf8pMTH/KTE5/ykxOf8pMTH/KTEx/ykpMf8xMTH/KSkx/ykpMf8pMTH/KSkx/yEhKf8hKSn/KSkp/ykpMf8pKTH/MSkx/ykpMf8hMTH/ITEx/ykpMf8pMTH/KSkx/ykpMf8pMTH/KTEx/zExMf8xKTH/ISkp/yEhKf8hKSn/ISEh/xghIf8hISH/ISEp/xgYIf8YGCH/EBgh/xgYIf8QISH/GCEh/xgYIf8YGCH/GCEh/xghIf8hISn/GCEh/xghIf8YISH/GBgh/xgYIf8QGBj/GBgh/xAYGP8QEBj/EBgY/xgYGP8YGCH/GCkx/xghIf8hKTH/KTE5/zlCUv9CQlL/OUpS/0Jaa/9KUmP/QlJj/zlKWv9CUlr/MTlK/zE5Sv85QlL/Skpa/0pKWv85OUr/QjlK/ylCUv8xSlr/KTlC/zFCSv8xQlL/KUJC/zExQv85OUr/OSlC/yEhKf8xQlL/MTlK/ylKUv85Y2P/QoRr/1KMY/9SlGP/ : 0 : 38 : 324;256;347;295
DELAY : 400
Mouse : 577 : 447 : LeftButtonDown : 0 : 1 : 0
DELAY : 110
Mouse : 577 : 447 : LeftButtonUp : 0 : 1 : 0
DELAY : 1200
LABEL : NOT-BOILING
IF IMAGE : Qk02AwAAAAAAADYAAAAoAAAAGAAAAAgAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAACP8AAAj/AAD//wAACP8AAAj/AAAA/wAAAP8AAP//AAAI/wAACP8AAP//AAAI/wAACP8AAAj/AAAI/wAACP8AAP//AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAD//wAACP8AAAj/AAAA/wAAAP8AAP//AAAI/wAACP8AAP//AAAI/wAACP8ACAj/AAgI/wAICP8AAP//AAAI/wAICP8ACAj/AAD//wAA//8AAP//AAAI/wAACP8AAAj/AAD//wAACP8AAAj/AAAI/wAACP8AAP//AAAI/wAACP8AAP//AAAI/wAACP8AAAj/AAgI/wAACP8AAP//AAAI/wAICP8AAP//AAgI/wAICP8ACAj/AAAI/wAACP8ACAj/AAD//wAACP8AAAj/AAAI/wAACP8AAP//AAAI/wAACP8AAP//AAAI/wAACP8AAAj/AAAI/wAACP8AAP//AAAI/wAACP8AAP//AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAD//wAA//8ACAj/AAAI/wAACP8AAP//AAAI/wAACP8AAP//AAAI/wAACP8AAAj/AAAI/wAICP8AAP//AAgI/wAICP8AAP//AAgI/wAICP8AAAj/AAD//wAA//8AAP//AAAI/wAACP8AAP//AAD//wAA//8AAAj/AAAA/wAAAP8AAP//AAAI/wAACP8AAAj/AAAI/wAICP8AAP//AAgI/wAICP8ACAj/AAD//wAA//8AAP//AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/ : 0 : 40 : 0 : 350;850;500;50
COMMENT : NOT-BOILING
Mouse : 581 : 430 : Move : 0 : 0 : 0
DELAY : 400
Mouse : 581 : 416 : LeftButtonDown : 0 : 1 : 0
DELAY : 110
Mouse : 581 : 416 : LeftButtonUp : 0 : 1 : 0
DELAY : 62
Mouse : 1124 : 729 : Move : 0 : 0 : 0
DELAY : 250
GOTO : ADD-CAULDRON
ENDIF
