COMMENT : V3 - Add to check right dragon spawn area
COMMENT : V3 - Improve timings for regen and faster response
COMMENT : V3 - Left click area 6px down.
REPEAT : 99999 : 0 : 0 : Enter the number of iterations: : 0 : 0
COMMENT : F3=Food - 10 min (do  9)
DELAY : 40
Keyboard : F3 : KeyDown
DELAY : 90
Keyboard : F3 : KeyUp
DELAY : 40
REPEAT : 3 : 0 : 0 : Enter the number of iterations: : 0 : 0
COMMENT : F2=WWT - 3 min
DELAY : 40
Keyboard : F2 : KeyDown
DELAY : 90
Keyboard : F2 : KeyUp
DELAY : 200
COMMENT : F4=Drag ess - do here cos timings screwed.
Keyboard : F4 : KeyDown
DELAY : 90
Keyboard : F4 : KeyUp
REPEAT : 5 : 0 : 0 : Enter the number of iterations: : 0 : 0
COMMENT : F1=Regen totem - 60s
DELAY : 40
Keyboard : F1 : KeyDown
DELAY : 90
Keyboard : F1 : KeyUp
DELAY : 500
REPEAT : 11 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk36CAAAAAAAADYAAAAoAAAAIQAAABEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/xgYCP8YGAj/GBgI/xgYEP8YGBD/AAAA//////8AAAD/GBgI/yEYCP8YGAj/GBgI/wAAAP//////AAAA/xgQAP8YEAD/AAAA/////////////////wAAAP8YEAD/GBAA/xgQAP8YEAD/AAAA//////8AAAD/EBAA/xAIAP8QCAD/GBgI/xgYCP8YGAj/GBAA/xgYEP8YGBD/AAAA//////8AAAD/GBAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8AAAD//////wAAAP8AAAD/AAAA//////8AAAD/GBAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xAIAP8QCAD/GBgI/xgYCP8YGAj/GBgI/xgQAP8YEAD/AAAA//////8AAAD/GBAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xAIAP8QCAD/GBgI/xgYCP8YGAj/ISEI/xgQAP8YEAD/AAAA//////8AAAD/GBAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgIAP8YCAD/GBgI/xgYEP8YGAj/GBgQ/xgYEP8YGBD/AAAA//////8AAAD/GBAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YCAD/GBgI/yEYEP8YGBD/GBgI/xgYCP8hIRD/AAAA//////8AAAD/GBAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/GBgI/yEYCP8YEAD/GBAA/xgQAP8YGAj/AAAA//////8AAAD/GBAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/xgYCP8YEAD/GBAA/wAAAP8YEAD/AAAA//////8AAAD/GBAA/xgQAP8AAAD/GBAA/wAAAP//////AAAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/AAAA/xgYCP8YEAD/AAAA//////8AAAD/AAAA//////8AAAD/GBAA/wAAAP//////AAAA/wAAAP//////AAAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/AAAA//////8AAAD/GBAA/xgQAP8YEAD/AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA//////8AAAD/GBAA/xgQAP8AAAD//////wAAAP//////AAAA/wAAAP//////AAAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/AAAA//////8AAAD/GBAA/xgQAP8YEAD/AAAA/xgQAP8YEAD/GBAA/xgQAP8AAAD///////////8AAAD/GBAA/xgQAP8YEAD/AAAA////////////AAAA/xgQAP8AAAD//////wAAAP8AAAD/AAAA//////8AAAD/GBAA/xgQAP8YEAD/AAAA//////8AAAD/GAgA/xgIAP8YEAD//////wAAAP8YEAD/GBAA/xgQAP8YEAD/AAAA//////8AAAD/GBAA/xgQAP8YEAD/GBAA/wAAAP//////AAAA/xgQAP8YEAD/AAAA/////////////////wAAAP8YCAD/GAgA/xgIAP8AAAD//////wAAAP8YCAD/GAgA/xgIAP8YCAD/AAAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/wAAAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8AAAD/GBAA/xgQAP8YEAD/GBAA/wAAAP8AAAD/AAAA/xgIAP8YCAD/GAgA/xgIAP8YCAD/AAAA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YEAD/EBAA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/ : 0 : 80 : 0 : 205;93;111;99
Mouse : 182 : 124 : Move : 0 : 0 : 0
DELAY : 90
Mouse : 0 : 0 : Click : 0 : 1 : 0
Mouse : C-1 : C-2 : Move : 0 : 0 : 0
DELAY : 90
Mouse : 0 : 0 : Click : 0 : 1 : 0
ENDIF
IF IMAGE : Qk3eAwAAAAAAADYAAAAoAAAAEgAAAA0AAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAQjkQ/0I5EP8AAAD//////wAAAP9KSiH/Skoh/0JCIf9CQiH/QkIh/0JCIf9KQiH/QkIh/zkxAP85KQD/OSkA/zkpAP85KQD/QjkQ/wAAAP//////AAAA/0JCIf9CSiH/Skoh/0pKIf9CSiH/QkIh/0JCIf9CQiH/QkIh/0JCIf85MQj/OSkA/zkpAP85KQD/QkIh/wAAAP//////AAAA/0JCGP9CQiH/Qkoh/0JKIf9CSin/QkIp/wAAAP9KQiH/QjEI/0IxCP85MQj/OTEI/zkpAP8AAAD/QkIh/wAAAP//////AAAA/0JCIf9CQhj/QkIh/0JKIf9CQin/AAAA//////8AAAD/OTEI/zkxCP85OQj/OTEQ/wAAAP//////AAAA//////8AAAD/QkIh/0JKKf9CSin/Qkoh/0JCIf9CSiH/AAAA//////8AAAD/QkIh/zkxCP85KQD/OSkA/wAAAP//////AAAA//////8AAAD/OTEA/0JCKf9CSin/Qkoh/zk5CP85MQD/AAAA//////8AAAD/OTkI/zkxAP85KQD/OSkA/wAAAP//////AAAA//////8AAAD/QkIh/zkxCP85OQD/Qkop/zk5CP85OQj/AAAA//////8AAAD/OTkI/zk5CP85MQD/OSkA/wAAAP//////AAAA//////8AAAD/SlIh/zk5CP85OQj/OTkI/zkxAP85OQj/AAAA//////8AAAD/QjkI/zk5CP85KQD/OSkA/wAAAP//////AAAA//////8AAAD/Qkop/0JKKf9CSin/OTkI/zk5CP85OQj/AAAA//////8AAAD/OTEA/zk5CP85MQD/OTkA/wAAAP//////AAAA//////8AAAD/QkIh/0JCIf9KUin/Qkop/0I5CP85MQD/AAAA//////8AAAD/OTEA/zkxAP85MQD/OTkI/wAAAP//////AAAA//////8AAAD/QjkQ/0I5EP9CQhj/OTkI/wAAAP85MQD/AAAA//////8AAAD/OTEA/zkxAP8AAAD/OTEA/wAAAP//////QjkQ/wAAAP//////AAAA/zkxCP85MQj/AAAA//////8AAAD/AAAA//////8AAAD/OTEA/wAAAP//////AAAA/wAAAP//////SkIY/wAAAP//////AAAA/zkxAP85MQD/OSkA/wAAAP//////AAAA//////8AAAD/OTEA/zkxAP8AAAD//////wAAAP////// : 0 : 80 : 0 : 248;79;66;36
Mouse : 182 : 124 : Move : 0 : 0 : 0
DELAY : 90
Mouse : 0 : 0 : Click : 0 : 1 : 0
Mouse : C-1 : C-2 : Move : 0 : 0 : 0
DELAY : 90
Mouse : 0 : 0 : Click : 0 : 1 : 0
ENDIF
IF IMAGE : Qk26CQAAAAAAADYAAAAoAAAAHQAAABUAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAEBAA/xAQAP8QEAD/EBAA/xAQAP8QEAD/EBAA/xAQAP8QEAD/EBAA/xAQAP8QEAD/EBAA/xAQAP8QCAD/EAgA/xAIAP8QCAD/EAgA/wAAAP8Ae///AAAA/xAIAP8QCAD/EAgA/xAQAP8QCAD/EAgA/xAIAP8QEAD/EBAA/xAQAP8QEAD/EBAA/xAQAP8QEAD/EBAA/xAQAP8YEAD/GBAA/xAQAP8QEAD/EBAA/xAQAP8QCAD/EAgA/xAIAP8QCAD/EAgA/wAAAP8Ae///AAAA/xAQAP8QEAD/EBAA/xAQAP8QCAD/EAgA/wAAAP8QEAD/EBAA/xAQAP8QEAD/EBAA/xAQAP8AAAD/EBAA/xgQAP8YEAD/GBAA/wAAAP8AAAD/AAAA/xAQAP8QCAD/EAgA/xAIAP8QCAD/AAAA/wB7//8AAAD/EBAA/xAQAP8YEAD/GBAA/xgQAP8YCAD/AHv//wAAAP8QEAD/EAgA/xAIAP8QEAD/AAAA/wB7//8AAAD/GBAA/xgQAP8AAAD/AHv//wB7//8Ae///AAAA/xAIAP8QCAD/EAgA/xAIAP8AAAD/AHv//wAAAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8Ae///AAAA/xgQAP8QEAD/GBAA/xgQAP8AAAD/AHv//wAAAP8YEAD/AAAA/wB7//8AAAD/AAAA/wAAAP8Ae///AAAA/xAIAP8QCAD/EAgA/xAIAP8AAAD/AHv//wAAAP8QEAD/GBAA/xgQAP8YEAD/GBAA/wB7//8AAAD/GBAA/xgQAP8YEAD/GBAA/wAAAP8Ae///AAAA/wAAAP8Ae///AAAA/xgQAP8YEAD/EBAA/wAAAP8Ae///AAAA/xAIAP8QCAD/EAgA/wAAAP8Ae///AAAA/xAQAP8YEAD/GBAA/xgQAP8QEAD/AHv//wAAAP8YEAD/GBAA/xgQAP8YEAD/AAAA/wB7//8AAAD/AAAA/wB7//8AAAD/GBAA/xgQAP8YEAD/AAAA/wB7//8AAAD/EAgA/xAIAP8QCAD/AAAA/wB7//8AAAD/EAgA/xAIAP8QEAD/EBAA/xAIAP8Ae///AAAA/xgQAP8YEAD/GBAA/xgQAP8AAAD/AHv//wAAAP8AAAD/AHv//wAAAP8YEAD/GBAA/xgQAP8AAAD/AHv//wAAAP8QCAD/EAgA/xAIAP8AAAD/AHv//wAAAP8YEAD/EBAA/xgQAP8QEAD/GAgA/wB7//8AAAD/GBAA/xgIAP8YCAD/GAgA/wAAAP8Ae///AAAA/wAAAP8Ae///AAAA/xgQAP8YEAD/GBAA/wAAAP8Ae///AAAA/xgQAP8YEAD/GBAA/wAAAP8Ae///AAAA/xgQAP8YEAD/EBAA/xAQAP8QCAD/AHv//wAAAP8YEAD/GBAA/xgIAP8YCAD/AAAA/wB7//8AAAD/AAAA/wB7//8AAAD/GBAA/xgQAP8YEAD/AAAA/wB7//8AAAD/GBAA/xgQAP8YEAD/AAAA/wB7//8AAAD/GBAA/xgQAP8QEAD/EBAA/xgIAP8Ae///AAAA/xgQAP8YEAD/AAAA/xgQAP8AAAD/AHv//wAAAP8AAAD/AHv//wAAAP8YEAD/GBAA/xgQAP8AAAD/AHv//wAAAP8YEAD/GBAA/xgQAP8AAAD/AHv//wAAAP8YEAD/GBAA/xAQAP8QEAD/EAgA/wB7//8AAAD/GBAA/wAAAP8Ae///AAAA/wAAAP8Ae///AAAA/wAAAP8Ae///AAAA/xgQAP8YEAD/GBAA/wAAAP8Ae///AAAA/xgQAP8YEAD/AAAA/wB7//8AAAD/GBAA/xgQAP8YEAD/GBAA/xgIAP8QCAD/AHv//wAAAP8YEAD/GBAA/wAAAP8Ae///AAAA/wB7//8AAAD/AAAA/wB7//8AAAD/GBAA/xgQAP8YEAD/AAAA/wB7//8AAAD/GBAA/xgQAP8AAAD/AHv//wAAAP8YEAD/GBAA/xgQAP8YEAD/GAgA/xAIAP8Ae///AAAA/xgQAP8YEAD/GBAA/wAAAP8Ae///AHv//wAAAP8YEAD/AAAA/wB7//8AAAD/AAAA/wAAAP8Ae///AAAA/xgQAP8YEAD/GAgA/wAAAP8Ae///AAAA/xgQAP8YEAD/GBAA/xgQAP8YCAD/GAgA/wB7//8AAAD/GAgA/xgIAP8YEAD/GBAA/wAAAP8Ae///AAAA/xgQAP8YEAD/AAAA/wB7//8Ae///AHv//wAAAP8YEAD/GBAA/xgQAP8AAAD/AHv//wAAAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/AAAA/xgIAP8YCAD/GAgA/xgIAP8YEAD/GBAA/wAAAP8YEAD/GBAA/xgQAP8YEAD/AAAA/wAAAP8AAAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8AAAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YEAD/GAgA/xgIAP8YCAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgQAP8YEAD/GBAA/xgIAP8YCAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgIAP8YCAD/GAgA/xAIAP8QCAD/EAgA/xAIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YCAD/GBAA/xgIAP8YCAD/GAgA/xgIAP8YCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgQAP8YEAD/GBAA/xgQAP8YEAD/GBAA/xgQAP8YCAD/GBAA/xgQAP8YCAD/ : 0 : 80 : 0 : 290;71;87;136
Mouse : 182 : 124 : Move : 0 : 0 : 0
DELAY : 90
Mouse : 0 : 0 : Click : 0 : 1 : 0
Mouse : C-1 : C-2 : Move : 0 : 0 : 0
DELAY : 90
Mouse : 0 : 0 : Click : 0 : 1 : 0
ENDIF
DELAY : 2450
ENDREPEAT
ENDREPEAT
ENDREPEAT
DELAY : 5700
ENDREPEAT
