SET CLIPBOARD : 10 : 0 : Please enter the text to store in clipboard:
COMMENT : V1 - based on sand golems
COMMENT : Start bottom right corner
COMMENT : F1=regen, F2=WWT, F3=GFP, F4=Crate, F5=Warr totem
COMMENT : F6=Dis resist, F7=BB, F11=Bag with WWT
LABEL : START-LAB
DELAY : 100
LABEL : Kill Bar - top
Keyboard : F2 : KeyPress
DELAY : 100
Keyboard : F1 : KeyPress
DELAY : 100
REPEAT : 2 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 152;191;466;303
COMMENT : Middle
DELAY : 25
Mouse : C19 : C37 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 3000
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 285;230;256;183
COMMENT : Centre
DELAY : 50
Mouse : C17 : C35 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 3500
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 113;213;675;289
COMMENT : Middle
DELAY : 25
Mouse : C20 : C35 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 3000
ENDIF
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 350;254;207;234
COMMENT : Red
DELAY : 50
Mouse : C8 : C35 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 389;210;408;219
COMMENT : Right
DELAY : 50
Mouse : C15 : C40 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C10 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 3500
ENDIF
IF IMAGE : Qk22EAAAAAAAADYAAAAoAAAAWAAAAAwAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP//////AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/////////////////wAACP8AAAj/AAAA//////8AAAj/AAAI/wAICP8AAAj/AAAI//////8ACAj/AAAI//////8AAAj/////////////////AAAI/wAICP8AAAj/AAAI/wAACP8AAAj/////////////////AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/////////////////wAICP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/////////////////wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/////////////////wAACP8AAAD/AAAA/wAACP8AAAj//////wAACP8ACAj/AAgI/wAACP8AAAj/AAgI//////8ACAj/AAgI/wAICP//////AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8ACAj/AAgI/wAACP///////////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP//////AAAI/wAICP8ACAj/AAgI//////8ACAj/AAgI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAAI//////8ACAj/AAgI/wAICP8ACAj/AAAI//////8AAAj/AAAI/wAACP//////AAAI//////8ACAj/AAgI/wAICP8AAAj//////wAACP8ACAj/AAgI/wAICP8AAAj//////wAACP8ACAj//////wAACP8AAAj/AAAI/wAICP8ACAj//////wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI//////8ACAj/AAgI/wAICP8AAAj/AAAI//////8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAgI//////8ACAj/AAgI/wAICP8AAAj/AAAA//////8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAACP//////AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8ACAj//////wAACP//////AAgI/wAICP8ACAj/AAAI//////8AAAj/AAgI/wAICP8ACAj/AAgI//////8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP//////AAgI/wAICP8ACAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP//////AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8AAAj//////////////////////////////////////wAACP8ACAj/AAgI/wAICP//////AAAI/wAICP8ACAj/AAgI/wAICP//////AAAI/wAACP8ACAj/AAgI/wAACP//////AAAI/wAACP//////////////////////////////////////AAAI/wAACP//////AAgI/wAICP8AAAj/AAgI/wAICP8ACAj//////wAACP8AAAj//////////////////////////////////////wAACP8AAAj//////wAICP8ACAj/AAgI/wAACP8AAAj//////wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////////////////////////////////////wAICP8ACAj/AAgI/wAACP8AAAj/AAgI/wAICP8ACAj/AAAI//////8AAAj/AAgI/wAACP8AAAj/AAAI//////8ACAj/AAgI/wAICP//////AAAI//////8AAAj/AAgI/wAICP8ACAj//////wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj//////wAICP8ACAj/AAgI/wAICP8ACAj/AAgI//////8ACAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8ACAj/AAgI//////8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI//////8ACAj/AAAI/wAACP8AAAj/AAgI//////8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAgI/wAICP8ACAj//////wAACP//////AAAI/wAICP8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI//////8AAAj/AAAI/wAICP8ACAj/AAgI//////8AAAj/AAAI//////8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP//////AAgI/wAICP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAgI/wAICP//////AAgI/wAICP8ACAj/AAgI/wAICP//////AAgI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAICP//////AAgI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAgI//////8AAAj/AAAI/wAICP//////AAgI/wAICP8ACAj//////wAICP8AAAj/AAAI//////8AAAj/AAAI/wAACP///////////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj//////wAICP8ACAj/AAgI//////8AAAj/AAAI/wAACP///////////wAACP8ACAj/AAgI/wAICP8ACAj//////wAICP8ACAj/AAgI//////8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj///////////8AAAj/AAAA/wAACP8AAAj//////wAICP8ACAj/AAgI//////8ACAj/AAgI/wAICP//////AAgI/wAICP8ACAj/AAAI//////8ACAj/AAgI/wAICP//////AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/////////////////AAgI/wAICP8ACAj//////wAICP8AAAj/AAAA/wAACP8AAAj//////wAACP8AAAj//////wAACP////////////////8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP////////////////8AAAj/AAAI/wAACP8AAAj//////wAACP////////////////8ACAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/////////////////AAAI/wAACP8AAAD/AAAA//////8AAAj//////////////////////wAACP8AAAj/AAAI/wAACP8AAAj/////////////////AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/////////////////AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/ : 0 : 30 : 0 : 82;796;169;32
COMMENT : Check if still targetting and delay moving off
Keyboard : F12 : KeyPress
DELAY : 2500
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 284;64;280;519
COMMENT : Middle + top/btm
DELAY : 50
Mouse : C16 : C40 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C10 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 3500
ENDIF
LABEL : Finish-Off
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 350;254;207;234
DELAY : 50
Mouse : C13 : C35 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
GOTO : Skip-targetting
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 270;203;343;306
DELAY : 50
Mouse : C10 : C40 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
LABEL : Skip-targetting
IF IMAGE : Qk3CCgAAAAAAADYAAAAoAAAAGwAAABkAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/CBgY/xAxQv8YSlr/IVpz/yFac/8YSlr/EDFC/wgYGP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAQEP8YSlL/MWuE/0qctf+Ezuf/lN7v/5Te7/+Ezuf/UqW9/yljc/8YQlL/AAgQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/CBgh/zFrhP9Spb3/a7XG/zlja/8YKTH/AAAA/wAAAP8hMTH/SnN7/5TW5/9KpbX/IVJr/wgQGP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8IEBD/OYSc/1Klvf9KhJT/CBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/xAYIf9zpbX/a73O/yFSa/8ACBD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xc4T/SqW1/zFjc/8AAAD/AAAA/wAAAP8AAAj/AABj/wAAUv8AAAD/AAAA/wAAAP8AAAD/Y5Sl/1qtxv8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/AAAA/wAAAP8AAAD/AAAA/xApKf9Spb3/OXuU/wAAAP8AAAD/AAAA/wAAGP8AAJT/AACl/wAAlP8AAGv/AAAI/wAAAP8AAAD/AAgI/5TW5/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//AAAA/wAAAP8AAAD/AAAA/zFja/9KnLX/GDFC/wAAAP8AAAD/AAAQ/wAAtf8AAM7/AADO/wAAtf8AAJz/AABz/wAACP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/0qUpf85e5T/CBAY/wAAAP8AAAD/AAC1/wAA3v8AAO//AADv/wAA5/8AAL3/AACc/wAAa/8AAAD/AAAA/wAAAP8AAAD/AABr/wAAxv8AAOf/AADn/wAA5/8AAOf/AAAA/wAAAP8AAAD/AAAA/2Otvf8pa4T/AAAA/wAAAP8AAGv/AADv/wAA9/8AAP//AAD//wAA9/8AAOf/AAC9/wAAnP8AADH/AAAA/wAAAP8AAAD/SkrW/5SU7/8AAM7/AADG/wAAxv8AAMb/AAAA/wAAAP8AAAD/AAAA/2u1zv8pa3v/AAAA/wAAAP8AAOf/AAD//wAA//8AAP//AAD//wAA//8AAPf/AADe/wAArf8AAHv/AAAA/wAAAP8AAAD/Skre/9bW9/+UlO//lJTv/5SU7/+UlO//AAAA/wAAAP8AAAD/AAAA/2Olvf8xc4z/ABAQ/wgIIf85Of//ISH//xAQ//8ICP//CAj//wgI//8AAP//AADv/wAAzv8AAKX/AAAI/wAAAP8AAAD/AABr/0pK5/9KSu//Skrv/0pK7/9KSu//AAAA/wAAAP8AAAD/AAAA/0pzhP9ClK3/ECkx/wgIIf9zc///Y2P//0JC//8xMf//OTn//0JC//85Of//GBj//wAA5/8AAMb/AAAQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yExOf9zxtb/IVJr/wAAAP+MjM7/paX//4yM//9zc///hIT//5SU//+UlP//a2v//xgY//8AAMb/AAAA/yFSa/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/AAAA/wAAAP8AAAD/AAAA/wAAAP9rpa3/Spy1/xg5Sv8YGCn/lJS9/62t9/9zc8b/KSlK/zExSv+UlMb/nJz//0JCxv8AACH/KVpr/1Klvf9rvdb/jNbv/5Te7/+U3u//lN7v/5Te7/+U3u//AAAA/wAAAP8AAAD/AAAA/wAAAP8QGCH/hM7e/zmMnP8YQlL/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8hUmP/SpSt/0qcrf8QGBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/ITE5/4zO5/9KnLX/IVpr/xApOf8IEBj/AAAA/wAAAP8IEBj/ECk5/ylre/9KnLX/WqW1/xAhKf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/xAhIf97rb3/jNbn/0qctf8pY3v/IVpz/yFac/8pa3v/UqW9/3vG3v9SlKX/CBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/KTlC/1qMlP97tcb/lN7v/5Te7/9rrb3/UnuM/yExOf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/ : 0 : 30 : 1 : 813;396;164;244
COMMENT : Test if diseased and BB
Keyboard : F7 : KeyPress
DELAY : 300
Mouse : 416 : 318 : Move : 0 : 0 : 0
DELAY : 120
Mouse : C1 : C4 : Move : 0 : 0 : 0
DELAY : 120
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 1900
Keyboard : F12 : KeyPress
DELAY : 100
ENDIF
IF IMAGE : Qk0uEAAAAAAAADYAAAAoAAAASQAAAA4AAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8IGBj/EDFC/xhKWv8hWnP/IVpz/xhKWv8QMUL/CBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAQEP8YSlL/MWuE/0qctf+Ezuf/lN7v/5Te7/+Ezuf/UqW9/yljc/8YQlL/AAgQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wgYIf8xa4T/UqW9/2u1xv85Y2v/GCkx/wAAAP8AAAD/ITEx/0pze/+U1uf/SqW1/yFSa/8IEBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wgQEP85hJz/UqW9/0qElP8IGBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/EBgh/3Oltf9rvc7/IVJr/wAIEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xc4T/SqW1/zFjc/8AAAD/AAAA/wAAAP8AAAj/AABj/wAAUv8AAAD/AAAA/wAAAP8AAAD/Y5Sl/1qtxv8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/UqW9/zl7lP8AAAD/AAAA/wAAAP8AABj/AACU/wAApf8AAJT/AABr/wAACP8AAAD/AAAA/wAICP+U1uf/lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/0qctf8YMUL/AAAA/wAAAP8AABD/AAC1/wAAzv8AAM7/AAC1/wAAnP8AAHP/AAAI/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP85e5T/CBAY/wAAAP8AAAD/AAC1/wAA3v8AAO//AADv/wAA5/8AAL3/AACc/wAAa/8AAAD/AAAA/wAAAP8AAAD/AABr/wAAxv8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/KWuE/wAAAP8AAAD/AABr/wAA7/8AAPf/AAD//wAA//8AAPf/AADn/wAAvf8AAJz/AAAx/wAAAP8AAAD/AAAA/0pK1v+UlO//AADO/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/ylre/8AAAD/AAAA/wAA5/8AAP//AAD//wAA//8AAP//AAD//wAA9/8AAN7/AACt/wAAe/8AAAD/AAAA/wAAAP9KSt7/1tb3/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/8xc4z/ABAQ/wgIIf85Of//ISH//xAQ//8ICP//CAj//wgI//8AAP//AADv/wAAzv8AAKX/AAAI/wAAAP8AAAD/AABr/0pK5/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//QpSt/xApMf8ICCH/c3P//2Nj//9CQv//MTH//zk5//9CQv//OTn//xgY//8AAOf/AADG/wAAEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/3PG1v8hUmv/AAAA/4yMzv+lpf//jIz//3Nz//+EhP//lJT//5SU//9ra///GBj//wAAxv8AAAD/IVJr/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8= : 0 : 30 : 1 : 813;396;164;244
COMMENT : Test life, pot, clear middle a little more
Keyboard : F3 : KeyPress
DELAY : 250
ENDIF
COMMENT : Check if out of ammo
IF IMAGE : Qk1aGAAAAAAAADYAAAAoAAAAZwAAAA8AAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////3v///97////e////wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///97////e////3v///8ACAj/e////wAACP8AAAj/e////3v///97////AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////e////3v///8AAAj/AAAI/wAICP8AAAj/AAAI/3v///8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/e////wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAD/AAAI/3v///8AAAj/AAgI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAICP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/e////wAACP8AAAj/AAgI/wAICP97////e////3v///8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////3v///8AAAj/AAAA/3v///8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8ACAj/AAAI/wAACP97////AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAD/AAAI/wAACP97////AAgI/wAICP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAgI/3v///8AAAj/AAAI/wAACP97////AAAI/wAAAP8AAAD/e////wAACP8AAAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAgI/wAICP97////AAgI/wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAgI/wAACP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAICP8ACAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAD/AAAI/wAACP97////AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAgI/wAICP8ACAj/e////wAICP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8ACAj/AAgI/wAACP97////AAAI/wAACP97////AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAA/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////3v///97////e////3v///97////e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAICP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAgI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP97////AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAICP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/e////wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAAAP8AAAj/AAAI/wAICP97////AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAAAP97////e////wAACP8AAAj/AAAI/3v///97////AAAI/wAACP8AAAj/e////wAACP8AAAj/e////3v///8AAAj/AAAI/wAACP97////e////wAICP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAAAP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAgI/wAICP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/3v///97////e////3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///97////e////wAACP8AAAj/AAAI/wAACP97////e////3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP97////e////3v///8ACAj/AAgI/3v///97////e////wAACP8AAAj/AAAI/3v///8AAAj/e////3v///97////AAAI/wAICP97////e////3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///97////e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/3v///8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP97////AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP97////e////3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/ : 0 : 30 : 0 : 333;875;771;102
PLAY MACRO : C:\Macros\logout.mcr
DELAY : 28842000
ENDIF
PLAY MACRO : C:\Macros\Hunting\test-dead.mcr
ENDREPEAT
IF CLIPBOARD EQUALS : 10 : 0 : 0
COMMENT : Restart circuit and do stuff that happens once a loop
Keyboard : F6 : KeyPress
DELAY : 125
Keyboard : F12 : KeyPress
DELAY : 100
Keyboard : F5 : KeyPress
DELAY : 125
Keyboard : F4 : KeyPress
DELAY : 100
SET CLIPBOARD : 9 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 8 : 0 : 0
Keyboard : Up : KeyDown
DELAY : 1000
Keyboard : Up : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 7 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 1500
Keyboard : Down : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 6 : 0 : 0
Mouse : 486 : 206 : Move : 0 : 0 : 0
DELAY : 100
Keyboard : Left : KeyDown
DELAY : 2000
Keyboard : Left : KeyUp
IF IMAGE : Qk2OCQAAAAAAADYAAAAoAAAAFwAAABoAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAGCEx/yExQv8pMUL/KTE5/yEpMf8pMTn/KTFC/xgYKf8YISn/GBgh/xghKf8YISn/GCEp/xghKf8YISn/GCEp/xghKf8YISn/GCEp/xghKf8YGCH/ISkx/yEpMf8QGCH/GCEx/yEpOf8hKTn/ISkx/yEpMf8pMTn/GBgh/xgYIf8YGCH/GCEp/yEpMf8YISn/GCEh/xgYIf8YISn/GCEx/xghKf8YISn/ISkx/xAYIf8hITH/KTFC/yEpOf8YITH/GCk5/xgpMf8YITH/GCEx/xghKf8QEBj/GBgh/xgYIf8YISn/GCEx/xghKf8YITH/ISEx/yEhMf8hITH/GCEp/xgYIf8QGCH/EBgY/yEpOf8xOUr/KTFK/ykxSv8hKTn/GCEx/xghKf8hKTn/KTE5/wgIEP8YISn/GBgh/xgYIf8YISn/GCEp/xghKf8YISn/ISkx/yEhMf8YISn/GCEp/xgYIf8YISn/ISk5/ykxOf8xOVL/KTlS/yExQv8hKTn/GCEx/yEpOf85QlL/ISkx/xgYIf8YISn/GBgh/xgYKf8YGCH/GCEp/xghKf8YISn/ISEx/xghKf8YISn/EBAY/yEpMf8hMUL/ISkx/yEpQv8hKUL/GCk5/xghMf8YISn/ISkx/zlCUv8xOUL/GBgh/xgYIf8QGCH/EBgh/xAYIf8YGCH/EBgh/xAYIf8YGCH/EBgh/xAQGP8QGBj/ITFC/ykxQv8hKTn/EBAh/xghMf8YISn/GCEx/xghKf8YISn/MTlK/yk5Sv8YGCH/GBgp/xgYIf8QGCH/GCEp/xgYKf8YISn/GCEp/xghKf8YGCH/EBgY/xAYIf8hMUL/KTlK/yExQv8YISn/ISk5/yEpOf8pMUL/ISk5/yEpOf8pMUL/MTlK/xghKf8YGCH/GBgh/xgYKf8YISn/GCEp/xghMf8YISn/GBgp/xAYIf8QGCH/EBgh/xgpOf8hMUL/GCk5/xghKf8YITH/GCEx/yEhMf8pMUL/KTFC/yEpOf8hKTn/GCEp/xghKf8YGCn/GBgp/xghKf8YGCn/EBgp/xAYKf8QGCH/EBgh/xAYIf8YISn/GCEp/xgpMf8hKTn/ISkx/ykxOf8hKTn/ISkx/yEpOf8hKTH/ISkx/yExOf8YISH/GCEp/xghMf8YISn/GCEx/yEhMf8YITH/GCEp/xgYIf8QEBj/GBgh/yExQv8YKTH/GCEx/yExQv8YITH/ISk5/yEpOf8hMTn/ISk5/xghMf8YISn/ISkx/xghKf8YGCH/GBgp/xgYKf8YISn/GCEp/yEhKf8hISn/GCEp/xAYIf8QGCH/GCk5/xAYIf8YGCn/ITFC/yEpOf8hKTn/KTE5/ykxQv8pMUL/KTlC/yEpOf8hKTn/EBgY/xgYIf8YISH/GBgh/xgYIf8QGCH/EBgh/xghKf8YISn/GBgp/xAYIf8YKTH/GCEp/xAQGP8hKTn/KTFK/ykxQv8pMUL/KTFC/yEpOf8pMUL/KTFC/yExQv8YKTH/GBgh/xgYIf8QGCH/GBgh/xgYIf8QEBj/EBgY/xgYIf8YISn/GBgh/ykxQv8pOUr/GCEx/yEpOf8hKTH/ISk5/ykxOf8pMUL/ISk5/yEpOf8xOUr/MTlK/ykxQv8YISn/GBgp/xghKf8hKTH/GCEp/xghKf8YGCH/GCEp/xghKf8QGBj/EBgY/yEpOf8pMTn/ITE5/yEpOf8hKTn/ISk5/ykxOf8hKTn/ISkx/zE5Qv8pMUL/KTFC/yEpMf8YISn/GCEp/yEpMf8hKTn/ITE5/yEpMf8YISn/GBgh/yEpMf8hKTH/KTE5/ykxQv8hKTn/KTFC/ykxQv8pMUL/GCEp/ykxQv8pKTn/KTFC/ykxQv8pMUL/ISk5/xAYIf8YGCH/GCEp/xAhKf8QGCH/GCEp/xghKf8YISn/ISkx/yEhMf8hKTn/KTFC/yk5Qv8hKTH/GCEx/yEhMf8YISn/EBAQ/xAQGP8pMUL/KTFK/ykxQv8pMUL/GBgh/xgYIf8YISn/ISEx/yEpMf8hKTH/GCEp/xgYIf8YISn/GCEx/yEpQv8pOUr/ITE5/ykxQv8hITH/GCEx/yEpOf8YITH/GCEp/yEpOf8xOUr/KTFK/ykxQv8YGCH/GCEp/yEpMf8hITH/GCEp/xghKf8YISn/GCEp/xghKf8YISn/GCE5/yExQv8YKTH/EBgh/yEpOf8pMUL/KTFC/ykxSv8xOUr/KTFC/yEpQv8xOUr/MTlK/xAYIf8YISn/ISkx/xghMf8YITH/GCEp/xgYIf8YISn/GCEx/xghKf8YITH/ISk5/xgpMf8YKTH/ISk5/ykxQv8xOUr/KTFC/yEpOf8hKTn/ISk5/ykxSv8pMUL/GBgh/xghKf8YISn/ISkx/yEpOf8hKTH/ISEx/xgYIf8hITH/ISkx/yEpOf8YITH/ISk5/yEpOf8hKTn/KSk5/ykxSv8pMUL/KTFC/yEpMf8YITH/ISk5/yEpQv8YISn/GCEp/xghKf8YISn/ISkx/yEhMf8YGCH/EBgh/yEpOf8hKTH/ITE5/xghMf8hMUL/ISkx/yEpOf8hKTn/ISlC/zE5Sv8xOVL/ISk5/xghMf8YKTn/ITFC/xghMf8YISn/GCEp/xghKf8YISn/ISEx/xghKf8YISn/ISEx/xghKf8hKTH/ISk5/ykxQv8hKTH/KTFC/yEpOf8YKTn/ISk5/ykxSv8hMUL/GCkx/xghMf8hKUL/GCEx/xAYIf8YGCH/GCEp/yEpMf8YITH/GBgp/xghKf8YGCH/GCEp/xghKf8YITH/KTFC/zExQv8xOUr/MTlK/zFCUv8hKTn/GCk5/yEpOf8pMUL/GCEx/xgpOf8YITH/EBgh/xAYIf8QGCH/GBgh/xgYIf8hITH/MTlC/ykpOf8YISn/EBgh/xAYIf8pMUL/MTlK/ykxQv8pKTn/KTFC/yk5Sv8xOUr/ISk5/yEpOf8hKTH/KTFC/yEpOf8hKTn/ISk5/yEhMf8hKTn/ISk5/ykxQv8xOUr/KTFC/yEpMf8YGCH/GCEp/ykxOf8xOUr/MTlK/ykxQv8hKTn/KTE5/ykxQv8xMUL/GCEx/xgpMf8hMTn/GCEx/xghMf8hKTn/ISk5/yEpOf8hITn/KTFC/zExQv8xMUL/KTFC/xghKf8hITH/ISkx/w== : 0 : 25 : 1 : 362;318;40;46
COMMENT : If not at very left then skip move down
INCREMENT CLIPBOARD : 3
ENDIF
ENDIF
IF CLIPBOARD EQUALS : 5 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 2000
Keyboard : Left : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 4 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 2000
Keyboard : Left : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 3 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 1500
Keyboard : Right : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 2 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 1500
Keyboard : Right : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 1 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 2000
Keyboard : Right : KeyUp
ENDIF
INCREMENT CLIPBOARD : 1
GOTO : START-LAB
