SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
LABEL : START-LAB
DELAY : 100
LABEL : Kill Bar - top
Keyboard : F5 : KeyPress
DELAY : 75
Keyboard : F4 : KeyPress
DELAY : 75
Keyboard : F2 : KeyPress
DELAY : 75
DELAY : 50
Keyboard : F1 : KeyPress
DELAY : 100
REPEAT : 3 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk2uAAAAAAAAADYAAAAoAAAACgAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABgA/wAYAP8AIQD/ACkA/wApAP8AKQD/ACkA/wApAP8AKQD/ACkA/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AIQD/ACEA/wAYAP8AIQD/ABgA/wAYAP8AEAD/ACEA/wAhAP8AKQD/ : 1 : 90 : 0 : 280;205;269;274
DELAY : 25
Mouse : C5 : C30 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 3000
ENDIF
IF IMAGE : Qk2uAAAAAAAAADYAAAAoAAAACgAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABgA/wAYAP8AIQD/ACkA/wApAP8AKQD/ACkA/wApAP8AKQD/ACkA/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AIQD/ACEA/wAYAP8AIQD/ABgA/wAYAP8AEAD/ACEA/wAhAP8AKQD/ : 1 : 90 : 0 : 19;320;771;307
DELAY : 25
Mouse : C12 : C30 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 3000
ENDIF
IF IMAGE : Qk2uAAAAAAAAADYAAAAoAAAACgAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABgA/wAYAP8AIQD/ACkA/wApAP8AKQD/ACkA/wApAP8AKQD/ACkA/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AIQD/ACEA/wAYAP8AIQD/ABgA/wAYAP8AEAD/ACEA/wAhAP8AKQD/ : 1 : 90 : 0 : 15;58;789;308
DELAY : 25
Mouse : C12 : C30 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 3000
ENDIF
COMMENT : Sandy ones
IF IMAGE : Qk3GAAAAAAAAADYAAAAoAAAADAAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAa4yl/2OMpf9jhJz/Y4Sc/1qEnP9ahJz/Y4Sc/1qEnP9jhJz/WoSc/2OEpf9jjKX/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/Y4yl/2uMpf9jjKX/Y4yl/2uMpf9jjKX/Y4yl/2OMpf9jjKX/Y4Sc/1qEnP9ahKX/ : 1 : 90 : 0 : 52;73;703;560
DELAY : 25
Mouse : C11 : C33 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 3000
ENDIF
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 350;254;207;234
DELAY : 25
Mouse : C3 : C35 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 2600
ENDIF
LABEL : Last Bit
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 270;203;343;306
DELAY : 25
Mouse : C8 : C40 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 2000
ENDIF
LABEL : Test for movement
ENDREPEAT
IF CLIPBOARD EQUALS : 16 : 0 : 0
SET CLIPBOARD : 15 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 15 : 0 : 0
IF IMAGE : Qk3mHQAAAAAAADYAAAAoAAAAMgAAACYAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAGDk5/xApKf8QKSn/ECEh/xgpKf8IEBD/ECEh/yFCQv9CY3P/Smt7/0pzjP85a2v/WnuU/1p7lP9jjKX/Y4Sc/2OMpf9rjKX/Y4yl/2uMpf9jjKX/Y4yl/2OMpf9jjKX/Y4Sl/1JzjP9ahJz/WoSc/yljc/9CWnP/OVpr/0Jjc/9CWmv/Qlpr/xhKWv9CWnP/GEpS/zFKWv8xQlL/EDE5/wgpMf8AECH/CBgp/xgpOf8QMTn/ISlC/xghMf8QOUL/EDlC/wgYKf8pSlL/ECEh/yE5Of8QISH/ECEh/wAICP8QKSn/GCkx/xgxMf9CY3P/QmN7/zlja/9Kc4z/UnOM/1JzjP9ahJz/WoSc/2OMpf9jhKX/Y4yl/2OMpf9jjKX/Y4yl/2OMpf9rjKX/UnuU/1JzjP9Ka4T/SmNz/yFaa/8IISn/CBgh/zFKWv85SmP/OUpa/zFKWv8xQlL/EDlC/xA5Sv8hWmv/GEpS/xAxOf8QMUL/CCEx/wAAAP8IGCH/CCEx/xApOf8YSlL/CCEp/xApMf8pSkr/ECEh/ylSUv8pSlL/GDE5/xgpKf8YMTn/GDE5/zlSY/85Umv/SmuE/0pre/9CY3v/SnOM/1JzjP9Se5T/UnuU/2OMpf9jhJz/Y4yl/2OMpf9jhKX/Y4Sl/2OMpf9Se5T/UnOE/1JrhP9CY3P/QlJr/wAACP8YMUL/IUpS/ylCSv8pOUr/KTlK/yE5Qv8IGCH/CCEp/xhCUv8hUlr/EBgp/yFKWv8QMTn/ECk5/xA5Sv8IKTH/EDE5/xhKUv8YITH/GBgh/xgxOf8pUlL/KUpK/yE5Qv8xWlr/KUpS/xg5Of8YOTn/IUJK/zlKWv85Wmv/QmNz/xAhKf8QGCH/SnOM/xAhKf8QEBj/Y4Sc/1qEnP9jhKX/Y4yl/2OEpf9jjKX/Y4yl/1J7lP9Sc4T/Smt7/yFaY/85UmP/CBgh/xAxOf8QMTn/EDlC/xAxQv8AGCH/AAAA/wAQGP8AAAD/AAAA/wAICP8AEBj/GEpS/xhKWv8AECH/ABAY/wghKf8ACBD/GEpa/wghKf8IEBD/IUpK/ylKSv8hQkL/GDk5/yFCQv8hQkL/IUJC/1qEnP8hSlL/KUJS/xgYKf9ahJz/EBAY/xhSUv8QMTn/EEpK/xAQIf9Se5T/Wnuc/1qEnP9ahJz/SlJj/2OEnP9ahJz/UnOM/1p7lP8pY3P/EBAY/zlSY/8QOUr/GCE5/yFaY/8QOUr/ABgh/xA5Sv8QKTn/AAAI/wAICP8ACAj/AAAA/wAQGP8QOUr/GEpS/wghKf8IISn/CBgh/wgpMf8hUmP/CCkx/wAAAP8AAAD/CAgQ/yFKSv8YMTH/GDE5/xApKf8QMTH/ECEp/xgxOf8YOTn/EBAY/xApKf8QMTn/GFJK/xhaUv8QMTn/EDEx/xAhKf8QGCH/Y4yl/1qEnP8xQkr/SlJj/1qEnP9CY3v/OVpz/yEpOf8YISn/GCEp/yFSWv8QGCn/GFJa/yFaY/8IMUL/CCkx/wgpOf8QOUr/EDlC/wgpOf8IKTn/EDlC/xhKUv8QOUr/KWNz/wAYIf8AEBj/EDFC/xA5Sv8IKTH/ECEp/yFCQv8hQkL/ITlC/wgQEP8pUlL/IUpK/yFCSv8hQkL/EBAY/xAhKf8QEBj/ECkx/xhKSv8QMTn/GGNa/xhKSv8QMTH/GFpS/xAQIf8QEBj/KTFC/zlCUv8pOUL/KTlC/ykxQv9CWnP/OVJj/ylCUv8YUlr/IVJj/wgQKf8hWmP/IVpr/xhKWv8hWmv/ABAY/wAhKf8IISn/CCEp/xA5Sv8QMTn/IVJa/xA5Qv8YSlL/ABgh/wghKf8YSlL/GEJS/wgYIf8hSkr/EBAY/xAQGP8IGBj/GCkx/yFCQv8pUlr/AAAA/yEYIf8hISn/GDk5/wgYGP8QKSn/ECkx/xAxOf8QKTH/GFpS/xhKSv8QKTH/GEpK/1p7lP8QEBj/ITFC/zlCUv9jhJz/UmuE/xgpKf8IEBj/EBAY/yFjc/8hUmP/KWtz/xBCUv8YUlr/EBgp/xBCSv8ACBD/CDE5/wgpOf8ACBD/EDE5/wAYIf8QECH/EDlK/wghKf8IKTH/EDE5/xA5Sv8pY3P/EBgx/ylSUv8QMTH/EDEx/xApMf8IISH/KVJa/yFCQv8YQkL/IUJK/yFKSv8YMTn/GCkp/xAYIf8QQkL/GFJS/xBCQv8QMTn/GFJS/xhrWv8QKTH/ECkx/xAYIf8xQkr/MUJK/0JSWv8pMUL/MTk5/xAhKf8QOTn/KWNz/yljc/8QGDH/AAAA/wghKf8QQkr/CCkx/wAYIf8QOUL/CCkx/wAQGP8IITH/ECEp/xhSSv8YQkr/ECkx/xApMf8hUmP/CCkx/yFaa/8pY2v/IUpK/yFKUv8QISH/ECEp/xg5Qv8pUlr/EBAY/ylSUv8QEBj/MWNr/yFCQv9jjKX/WoSc/xAQGP8QKTH/EEpK/xAxOf8QMTn/GHNj/xh7a/8YWlL/ECEp/xAYKf8QISn/EBgh/xAYIf8QOUL/GGNa/xAhKf8AAAD/AAAA/wAAAP8IKTH/CDEx/wg5Qv8QQkL/CDlC/xAhKf8QEBj/EBAY/xA5Of8QISn/GJRz/xhaUv8YUlL/EEJS/wAhKf8AAAD/CCkx/ylre/8pUlL/IUpK/wAICP8YMTH/AAAI/ylSUv8ACBD/ECkx/wgIEP8hSkr/EBAY/yk5Qv8pMUL/CBgh/wgQGP8QGCH/ECkx/xApMf8QKTH/GGNa/xhzY/8YWlL/GEpK/xhjWv8QMTH/CCkp/xAQGP8YUkr/EDFC/xAxMf8QECH/CCkp/wAYGP8AAAj/AAgY/xAhKf8IITH/GGta/xAxMf8QGCH/GIRr/xAhKf8YlHP/EDEx/wAYKf8IITH/ACEp/wAACP8AGCH/IVpj/ylSUv8QMTH/ECkp/ylSUv8pUlL/IUpK/yFKSv8AAAj/IUpK/yFKSv8QMTH/IUJK/ykxQv8YISn/EBAY/xhjWv8QOTn/EDlC/xApMf8QMTn/GGNS/xhrWv8YWlL/GFJS/xhSSv8QOTn/ECEp/xBKSv8QQkL/GHNj/xBCQv8QQkL/AAAI/wAYIf8QGCH/GHtr/wgYIf8YlHP/EEJC/xAYIf8YrYT/GGta/xApMf8Ya1r/EEpK/xAQGP8QOUr/CCkx/wAICP8QQkr/IUJC/xgYIf8YOTn/KVJa/yFCSv8QMTH/IUpK/wghIf8YOTn/CAgQ/xg5Of8YOUL/EBAY/ylKSv8ACBD/EEJC/xiUc/8Ye2P/GHNj/xBCQv8QQkL/EEJC/xBCQv8YUlL/GGta/xhjUv8Ya1r/GHNj/xhzY/8Yc2P/GFJK/xhKSv8Ya1r/AAgY/xAhKf8YrYT/ACEx/xhrWv8YhGv/GGta/xhaUv8YY1r/EBgh/xAYIf8YWlL/GGNa/xAYKf8QMTn/CDE5/wAIEP8hQkr/IUpK/yFCQv8pUlr/KVJa/xgYIf8IGBj/ECkx/xgQIf8YGCH/GDEx/yFCQv8YUkr/GFJS/xAQGP8QKTH/GIRr/xh7Y/8YY1r/GGNa/xhjWv8YY1r/GFJK/xA5Of8QSkr/GGNa/xhaUv8Yc2P/GEpK/xhzY/8Ye2v/ECkx/xiMc/8QQkL/ECkx/xicc/8Ya1r/GHtj/xhaUv8QSkr/CCkx/xAhKf8YhGv/GFpS/xAQGP8AGCH/CCEp/wAQGP8QMTn/EDFC/wgYIf8QKTH/ECkx/yFCSv8QKSn/GDlC/wgQGP8YMTH/EBAY/xAQGP8QMTn/EBAh/xhjWv8hvYz/GJx7/xiUc/8YnHv/GJx7/xiUe/8YjHP/GHNj/xh7Y/8YWlL/EEJC/xhaUv8YY1r/GGNa/xhjWv8YhGv/GJRz/xh7Y/8Yc2P/GIRr/xiMa/8YhGv/EEJC/xiUc/8QQkL/EDE5/xiEa/8YpXv/GGNS/xAYIf8AGCH/EBAY/wAYIf8ICBD/AAAA/wAACP8IGCH/GDEx/xhCQv8QMTH/IUpK/xAhIf8QKTH/ABAQ/zFjWv8QGCH/GIxz/xA5Of8ICBD/IUo5/xAYKf8YhGv/GIRr/xhaUv8QOTn/GIxz/xBCQv8ICBD/ECkx/xhjWv8YUlL/GJRz/xiMc/8YhGv/GHNj/xithP8YhGv/GFpS/xiEa/8QQkL/EBgh/xile/8Ya1r/GGNS/xice/8YlHP/GGta/xhrWv8YWlL/GFpS/xAQIf8ACAj/ECkp/xgxKf8AAAD/ABAY/wgYIf8QMTH/EDEx/xg5Of8hQkL/GBgh/xhaUv8QOTn/AAAA/zFjWv8QQkL/IcaM/xhSUv8QISn/GFJK/xhKSv8YjHP/GFpS/xBCQv8YnHv/GGNa/xA5Of8QKSn/GGta/xhSUv8YhGv/GJRz/xiMc/8YY1r/GIxr/xiUc/8YjHP/GHtr/xiEa/8QSkr/GGNS/xiMc/8QKTH/EEJC/xBCQv8YjGv/GFpS/xApMf8AAAD/AAgI/xAhIf8QKSH/ABAQ/wAACP8AGCH/CBgY/xAhKf8QKTH/IUJK/ylaWv8AGBj/ECkx/yHGjP8Ye2P/CBgh/zFjWv8YY1r/GJx7/xBKQv8QMTn/EEJC/xile/8YWlL/EDk5/xh7Y/8YWlL/GIxz/xA5Of8YY1r/GGta/xiMc/8QOUL/EBgh/xiMc/8YhGv/GHNj/xice/8YnHv/GK2E/yG9hP8YY1r/EBgh/xh7Y/8YSkr/EEJC/xApMf8QGCn/ECEp/xApIf8IEBD/AAAA/wAAAP8ACAj/ECEh/yFCOf8pUkr/GBgh/xhzY/8YrXv/GGNa/xAQGP8ACBD/EDk5/xi1hP8Yc2P/GFpS/xAhKf8Yc2P/GGNa/xAYKf8QOUL/GJRz/xiUc/8YjHP/GJR7/xice/8YpXv/GHtj/xile/8Ya1r/GFpS/xhjWv8Ya1r/GKV7/xhSSv8YSkr/GIxr/xiMa/8YnHv/GHNj/xAhKf8AEBD/EBAY/wgYGP8QGCH/AAAA/wAAAP8QISH/IUpC/wgYEP8ACAj/AAgI/wAAAP8AAAD/AAgI/xAhIf8QQkL/ECkp/xApMf8YlHP/GJx7/xhjUv8YUlL/EEpK/xiUc/8YMTH/ECEp/xiMc/8YjGv/EDE5/xh7Y/8YnHv/GGta/xiEa/8Yc2P/GHNj/xiMc/8Ye2v/GKV7/xhaUv8Ya1r/GIRr/xithP8YjHP/GGta/xhzY/8YjGv/EEpK/xhrWv8QGCH/AAAA/wAAAP8QISn/EBgp/zFjUv8AAAD/CBgQ/wAICP8ACAj/ABAQ/wgQEP8IGBD/CCEY/xApIf8YMSn/ECEh/xithP8Ye2P/GFpS/xBCQv8YUkr/GGtj/xgxOf8QGCn/IdaU/xBCQv8QMTn/GIRr/xiUc/8YUkr/EDk5/xApMf8QQkL/EDEp/xAhKf8QMSn/AAAA/xAhKf8YhGv/ABAI/wAQEP8QISn/GHNj/xiMc/8YpXv/GKWE/xile/8YhGv/GGtj/xhzY/8YjGv/GKV7/xiUc/8QKTH/ECEh/wAQCP8IEBD/CBAQ/xApKf8AAAD/AAgI/xAhIf8QISH/CBAQ/wgQEP8QKSn/ECEp/xiMc/8QISn/CCkp/xiUc/8Ye2P/EDE5/xAYIf8hzpT/EEpK/xhaUv8Ya1r/GFJK/xApMf8QQkL/EEJC/xhrWv8Ya1r/GIRr/xice/8YrYT/GHtj/xice/8YWlL/GEpK/xAQGP8IEBD/EBAY/xhzY/8YpXv/GIRr/xiEa/8YUkr/GGta/xiEa/8YY1r/CCEY/wAAAP8AAAD/EBgh/xAYIf8YMTH/EDEp/wAAAP8AAAD/CBgQ/xg5Mf8AEAj/CBgY/wgYGP8QOUL/IcaM/yFKUv8QKTH/IcaM/xAYIf8QMTH/GDkx/xhjWv8YMSn/EBAY/xBCQv8QOTn/GFJK/xhrWv8YhGv/GIRr/xiMa/8YhGv/GGNa/xAxOf8QMTn/GHtj/xBKSv8YrYT/GK2E/xhzY/8QKTH/CBgY/xApMf8YY1L/EDE5/xhzY/8YrYT/EDk5/xhaUv8YWlL/GGNa/xite/8YnHv/ECkx/wghGP8AAAD/CBgQ/wAAAP8IGBj/IUpC/wgYGP8ACAj/AAgI/xithP8YUlL/GBgh/xhaUv8QQkL/AAAA/wgYGP8AAAj/EBAY/yFCOf8hSkL/ECEp/xApMf8QEBj/ECEp/wAAAP8ACAj/AAAA/wAICP8IIRj/ECEh/xBCQv8Ya1r/ECEh/xAQIf8YSkr/GIxz/xithP8YjHP/GFpS/xAYIf8QQkL/GGta/xiUc/8YSkr/EDlC/xiEa/8YjHP/GHNj/xAxKf8QKSn/AAgI/wAICP8QISH/ECkh/wgYEP8pUkr/GDEp/wAICP8IEBD/GGta/xg5Of8YOTn/EBgh/wAYGP8AAAD/CCEp/yFSQv8xa2P/MWNa/yFCOf8YMSn/EDEp/wghGP8QMSn/CBgY/wAICP8ACAj/EBAY/xAhKf8QGCH/GGNa/xhaUv8YOTH/ECkh/xg5Of8YMSn/CBgQ/xAYIf8QKTH/EEJC/xhKSv8YUkr/GEpK/xhzY/8YhGv/IcaM/xAhKf8QMTH/GHNj/xiUc/8YlHP/GIxz/xhrWv8QKTH/ECEh/yE5Of8hSkL/EBgY/xgpIf8xWkL/KVI5/xgQIf8AAAj/ECEp/ylaUv8pWlL/KVpK/ylSSv8IEBj/AAgQ/wAAAP8hSkL/GDkx/xAYIf8YSkr/GIRr/xithP8hxpT/IdaU/xice/8YlHP/GIxr/xiUc/8YY1r/EBgp/wgQEP8hOTH/CCEY/xg5Mf8QGCH/EDE5/xBCQv8YUlL/EBAY/xhjUv8YhGv/AAgA/yFCOf8YlHP/GFJK/xhrWv8QKTH/EBgp/xApMf8QOTn/EDlC/xAhKf8QKSn/CBgY/zFaQv8pUjn/EBAQ/wghIf8IKSn/CCEp/wgYIf8ACBD/KVpK/wgYIf8hQjn/GDEp/xg5Mf8QISH/EBAY/xApMf8QMTn/EDE5/xApMf8QGCH/AAgI/xh7a/8QMTn/EDk5/xile/8hxoz/GIxz/xAxOf8IGBD/IUpC/yFKQv8ACAD/EBAY/xAQGP8IGBj/ECkx/xAQIf8AAAD/EBAY/yHWlP8QGCH/EBAY/xiMc/8YpXv/GJRz/xhSSv8QKTH/EBAY/ylKQv8QEBj/ITkp/yE5Kf8QKSn/CCkp/wghIf8AGBj/CBgY/xAhIf8YMTH/ECEh/wgYEP8AAAD/GDkx/xg5Mf8QISH/GEI5/wgYGP8QISH/IUpC/xgpKf8ACAj/GJRz/xAhKf8xa1r/GDkx/xAYIf8QQkL/GGNS/xA5Of8hQjn/KVpS/wAAAP8AAAD/AAgI/wgQEP8IGBD/ECkh/wghGP8QMSn/GLWE/xAhKf8AAAD/Ib2M/xAhKf8QQkL/GHNj/xiEa/8YhGv/EEpK/xAYIf8hOSn/CCEh/yFKQv8xWkL/IVJC/ylSSv8hSkL/IUJC/yFCOf8IGBD/CAgI/wgICP8hSkL/ABAQ/xAYIf8QQkL/GGta/xiUc/8YtYT/IcaM/xiEa/8YrYT/GHtj/xhzY/8QKTH/CBgY/yFKQv8YOTH/GDkx/yFCOf8pWlL/CBAQ/wAAAP8AEBD/AAgA/wAICP8AEBD/AAgI/xg5Mf8QQkL/EBAY/wAAAP8hzpT/ECEp/wgQEP8YpXv/EDE5/xhaUv8YY1L/GK2E/wgYGP8pWkL/OXNS/zFjSv85Y0r/MVpC/xAhIf8AAAD/CBgY/wAAAP8IGBj/ECkh/xg5Mf8AAAD/EBgp/xA5Of8QSkr/EEpK/xBCQv8QGCH/OXNr/xice/8QGCn/GHNj/yG9jP8YpXv/GFpS/xAYIf8IGBj/GDEp/zFjUv8ACAj/AAAA/wgYEP8ACAj/ECEY/wAAAP8AEBD/IUpC/xg5Mf8IGBD/ABAQ/xh7Y/8QISn/ECkh/xi1hP8xa2P/GHNj/xAxMf8QECH/ABAQ/zFzUv8xY0r/KUo5/ylKMf8AEBD/ABAQ/wAIIf8QEBD/AAAA/wgYGP8pUkr/GDEp/wAICP8ACAj/IUI5/xgxMf8QKSH/MWNS/xAhKf8QOTn/GK2E/xAhKf8YQjn/GDk5/xAxOf8YY1r/GGta/xApMf8QKSn/MWNS/wghGP8AAAD/ECkh/xApIf8QKSH/CBgY/wAQCP8hSjn/GDk5/xAhGP8QKSH/EBAY/xApIf8IIRj/EDk5/ylSSv8Ya1r/EEpK/wgYGP8QKSH/KWNK/ylSQv8pUjn/IUIx/wgIEP8pWlL/CDlK/xApIf8QKSn/GDkx/ylSSv8AEBD/CBAQ/xAYGP8QEBj/EEJC/xiMc/8hxpT/GK2E/xhKSv8YnHv/GFpS/xithP8QMTn/AAAA/xAhIf8QKSn/ABAQ/xAhIf8pUkr/GDEp/xApIf8YOTH/EDEp/wAICP8ACAj/ABAQ/xg5Mf8hQjn/ABAQ/xAxKf8ACAj/ABAQ/xgxKf8IEBD/IUI5/xAQIf8QGCH/AAAA/xAYEP8YOSn/GDkh/xg5Kf8xY1r/KVJK/wAQCP8QSjH/ECkh/xgxKf8YOTH/GDkx/xApKf8IGBD/ECkx/xhrWv8Yc2P/EEpK/xAYIf8QKSn/EBAY/xice/8hQjn/EEJC/yG9jP8YhGv/EBAY/wAAAP8AAAD/CBgQ/ylaSv8hSjn/ECkp/yFKQv8IEBD/ABAQ/xg5Mf8hQjn/GDkx/zFjUv8QIRj/ECEh/xApKf8AAAD/CBgQ/xAxKf8hQjn/ECkp/wAIAP8AAAD/GDkp/xApEP8YGEL/IRhr/zFSWv85c0r/ABgQ/wgpMf8AAAj/ECEh/xgxKf8QISH/AAgY/wAACP8ACAj/AAAA/ylKQv8QKTH/GHNj/xice/8Yc2P/GKV7/xhjUv8QMTn/IUo5/xhaUv8YjHP/EDE5/wAQEP8QMSn/IUI5/xg5Mf8hSkL/GDkx/xg5Mf8pUkr/IUpC/xApKf8IIRj/KVpS/xAxKf8QISH/GDEx/xg5Mf8ACAj/AAAA/xApIf8YMTH/AAgI/wgQEP8xa1L/IVIx/zE5Y/85MZT/QmNz/zFrQv8IMUL/ABgh/yFCOf8AAAD/ABgY/wgYMf8ACBD/EBAY/xApMf8Ya1r/GJRz/xiUc/8YY1L/EBgh/xAhKf8YhGv/EBAh/xithP8YlHP/EBAh/wAAAP8QISn/EBAY/wAAAP8AAAD/KVJC/xg5Mf8QKSH/IUpC/wAAAP8QKSH/IUI5/wgYEP8pUkr/ECkh/xg5Mf8QKSn/ECkh/xApKf8ACAj/CBgY/yE5Of8YKSn/CBgY/yljSv8pY0L/KWtC/zF7Sv8hQjH/CEo5/wAYEP8YOSn/ABgQ/wgpGP8AEBD/EDEp/wghGP8QEBj/EBAY/wgYGP8pUkL/EBgh/xBCQv8YY1r/GGtj/xice/8QMTn/EBAh/xBCQv8YlHP/GGNa/xAQGP8ACAj/AAgI/wAAAP8YQjn/CBgQ/xhCOf8hUkL/AAAA/xApKf8pWlL/CCEY/xg5Mf8hQjn/CBgY/yFCOf8QMSn/AAgA/wgYGP8QKSH/GDkx/wgICP8AEBD/IVI5/ylaQv8hUjn/KVJC/xgYQv85Y2P/IUo5/wAhGP8AGBD/AAgI/wAAAP8IGBj/CBgY/xApIf8YOTH/EBAh/xA5Qv8QUkr/EEpK/xA5Qv8QOUL/GIxz/xA5Of8Ye2v/EEJC/wAQEP8QKTH/EDE5/wAICP8AEBD/CBgY/xAhIf8IGBD/KVJK/xg5Mf8ACAj/EDEp/ylaUv8IIRj/ECkh/ylSSv8AEBD/CBgY/ylaUv8QISH/ABAQ/xAxKf8ICAj/AAAA/wgYGP8pMUr/GCFC/yFCKf8pUkL/QlJj/zlCe/8xSlL/AAAQ/wAICP8AEBD/AAgA/wgYGP8YMTH/IUI5/yFSQv8QEBj/EDk5/xhjWv8Yc2P/GFpS/xAxOf8YrYT/GFpS/xhjUv8QSkr/EDk5/xAQGP8QISH/AAgI/wAQEP8QKSH/CBgY/wghGP8pWlL/ABAQ/wAQEP8YMSn/MWta/xg5Mf8IGBj/KVJK/wghGP8AAAD/GDk5/ylSSv8IGBj/ABAQ/wgQEP8IGBj/GDEx/w== : 1 : 40 : 0 : 192;185;407;373
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 450
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
DELAY : 60
ENDIF
IF IMAGE : Qk0WHQAAAAAAADYAAAAoAAAAOAAAACEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAISEp/yFCQv8YOUL/GDE5/xgxMf8IEBD/KVJS/yFKSv8ACAj/GDEx/wAACP8pUlL/AAgQ/xApMf8ICBD/IUpK/xAQGP8pOUL/KTFC/wgYIf8IEBj/EBgh/xApMf8QKTH/ECkx/xhjWv8Yc2P/GFpS/xhKSv9CWuf/Umvv/wgpKf8QEBj/GFJK/xAxQv8QMTH/EBAh/wgpKf8AGBj/AAAI/wAIGP8QISn/CCEx/xhrWv8QMTH/EBgh/xiEa/8QISn/GJRz/xAxMf8AGCn/CCEx/wAhKf8AAAj/ABgh/yFaY/8hQkr/KUpS/yFCQv8YOTn/GDE5/xg5Of8pUlL/EDEx/xApKf8pUlL/KVJS/yFKSv8hSkr/AAAI/yFKSv8hSkr/EDEx/yFCSv8pMUL/GCEp/xAQGP8YY1r/EDk5/xA5Qv8QKTH/EDE5/xhjUv8Ya1r/GFpS/xhSUv8YUkr/EDk5/xAhKf8QSkr/EEJC/xhzY/8QQkL/EEJC/wAACP8AGCH/EBgh/xh7a/8IGCH/GJRz/xBCQv8QGCH/GK2E/xhrWv8QKTH/GGta/xBKSv8QEBj/EDlK/wgpMf8ACAj/EEJK/wghIf8AAAD/EDk5/xA5Of8YOTn/GDlC/yFCQv8YGCH/GDk5/ylSWv8hQkr/EDEx/yFKSv8IISH/GDk5/wgIEP8YOTn/GDlC/xAQGP8pSkr/AAgQ/xBCQv8YlHP/GHtj/xhzY/8QQkL/EEJC/xBCQv8QQkL/GFJS/xhrWv8YY1L/GGta/xhzY/8Yc2P/GHNj/xhSSv8YSkr/GGta/wAIGP8QISn/GK2E/wAhMf8Ya1r/GIRr/xhrWv8YWlL/GGNa/xAYIf8QGCH/GFpS/xhjWv8QGCn/EDE5/wgxOf8ACBD/CBgY/wAAAP8IKSn/ABAQ/xgxOf8YOUL/IUJK/yFKSv8hQkL/KVJa/ylSWv8YGCH/CBgY/xApMf8YECH/GBgh/xgxMf8hQkL/GFJK/xhSUv8QEBj/ECkx/xiEa/8Ye2P/GGNa/xhjWv8YY1r/GGNa/xhSSv8QOTn/EEpK/xhjWv8YWlL/GHNj/xhKSv8Yc2P/GHtr/xApMf8YjHP/EEJC/xApMf8YnHP/GGta/xh7Y/8YWlL/EEpK/wgpMf8QISn/GIRr/xhaUv8QEBj/ABgh/wghKf8AEBj/EDE5/xAxQv85c2P/MWNS/zFjUv8AGBj/IUJC/yFCQv8IGCH/ECkx/xApMf8hQkr/ECkp/xg5Qv8IEBj/GDEx/xAQGP8QEBj/EDE5/xAQIf8YY1r/Ib2M/xice/8YlHP/GJx7/xice/8YlHv/GIxz/xhzY/8Ye2P/GFpS/xBCQv8YWlL/GGNa/xhjWv8YY1r/GIRr/xiUc/8Ye2P/GHNj/xiEa/8YjGv/GIRr/xBCQv8YlHP/EEJC/xAxOf8YhGv/GKV7/xhjUv8QGCH/ABgh/xAQGP8AGCH/CAgQ/wAAAP8AAAj/CBgh/xgYCP8AEBD/ABgY/wAAAP8IGBj/ECEh/xgxMf8YQkL/EDEx/yFKSv8QISH/ECkx/wAQEP8xY1r/EBgh/xiMc/8QOTn/CAgQ/yFKOf8QGCn/GIRr/xiEa/8YWlL/EDk5/xiMc/8QQkL/CAgQ/xApMf8YY1r/GFJS/xiUc/8YjHP/GIRr/xhzY/8YrYT/GIRr/xhaUv8YhGv/EEJC/xAYIf8YpXv/GGta/xhjUv8YnHv/GJRz/xhrWv8Ya1r/GFpS/xhaUv8QECH/AAgI/xApKf8YMSn/AAAA/wAQGP8IGCH/ABAY/wAACP8AGBj/AAAA/wAAAP8AAAj/EDEx/xAxMf8YOTn/IUJC/xgYIf8YWlL/EDk5/wAAAP8xY1r/EEJC/yHGjP8YUlL/ECEp/xhSSv8YSkr/GIxz/xhaUv8QQkL/GJx7/xhjWv8QOTn/ECkp/xhrWv8YUlL/GIRr/xiUc/8YjHP/GGNa/xiMa/8YlHP/GIxz/xh7a/8YhGv/EEpK/xhjUv8YjHP/ECkx/xBCQv8QQkL/GIxr/xhaUv8QKTH/AAAA/wAICP8QISH/ECkh/wAQEP8AAAj/ABgh/wgYGP8AISH/ECkx/wgYIf8ACBD/ABAQ/wghIf8QISn/ECkx/yFCSv8pWlr/ABgY/xApMf8hxoz/GHtj/wgYIf8xY1r/GGNa/xice/8QSkL/EDE5/xBCQv8YpXv/GFpS/xA5Of8Ye2P/GFpS/xiMc/8QOTn/GGNa/xhrWv8YjHP/EDlC/xAYIf8YjHP/GIRr/xhzY/8YnHv/GJx7/xithP8hvYT/GGNa/xAYIf8Ye2P/GEpK/xBCQv8QKTH/EBgp/xAhKf8QKSH/CBAQ/wAAAP8AAAD/AAgI/xAhIf8hQjn/KVJK/wAQEP8QMTH/EBAY/xBKSv8QKTH/GDE5/xgYIf8Yc2P/GK17/xhjWv8QEBj/AAgQ/xA5Of8YtYT/GHNj/xhaUv8QISn/GHNj/xhjWv8QGCn/EDlC/xiUc/8YlHP/GIxz/xiUe/8YnHv/GKV7/xh7Y/8YpXv/GGta/xhaUv8YY1r/GGta/xile/8YUkr/GEpK/xiMa/8YjGv/GJx7/xhzY/8QISn/ABAQ/xAQGP8IGBj/EBgh/wAAAP8AAAD/ECEh/yFKQv8IGBD/AAgI/wAICP8AAAD/AAAA/wAICP8QISH/EBAY/xApMf85c1L/EBgh/xiUc/8YpXv/EEJC/xApKf8QKTH/GJRz/xice/8YY1L/GFJS/xBKSv8YlHP/GDEx/xAhKf8YjHP/GIxr/xAxOf8Ye2P/GJx7/xhrWv8YhGv/GHNj/xhzY/8YjHP/GHtr/xile/8YWlL/GGta/xiEa/8YrYT/GIxz/xhrWv8Yc2P/GIxr/xBKSv8Ya1r/EBgh/wAAAP8AAAD/ECEp/xAYKf8xY1L/AAAA/wgYEP8ACAj/AAgI/wAQEP8IEBD/CBgQ/wghGP8QKSH/GDEp/xAhIf8QECH/EEJC/xiMa/8QOTn/IUJC/xhaUv8YrYT/GHtj/xhaUv8QQkL/GFJK/xhrY/8YMTn/EBgp/yHWlP8QQkL/EDE5/xiEa/8YlHP/GFJK/xA5Of8QKTH/EEJC/xAxKf8QISn/EDEp/wAAAP8QISn/GIRr/wAQCP8AEBD/ECEp/xhzY/8YjHP/GKV7/xilhP8YpXv/GIRr/xhrY/8Yc2P/GIxr/xile/8YlHP/ECkx/xAhIf8AEAj/CBAQ/wgQEP8QKSn/AAAA/wAICP8QISH/ECEh/wgQEP8IEBD/ECkp/xi1hP8QSkr/GGta/xiUc/8YjGv/EEJC/xAhKf8YjHP/ECEp/wgpKf8YlHP/GHtj/xAxOf8QGCH/Ic6U/xBKSv8YWlL/GGta/xhSSv8QKTH/EEJC/xBCQv8Ya1r/GGta/xiEa/8YnHv/GK2E/xh7Y/8YnHv/GFpS/xhKSv8QEBj/CBAQ/xAQGP8Yc2P/GKV7/xiEa/8YhGv/GFJK/xhrWv8YhGv/GGNa/wghGP8AAAD/AAAA/xAYIf8QGCH/GDEx/xAxKf8AAAD/AAAA/wgYEP8YOTH/ABAI/wgYGP8IGBj/ECEp/xhzY/8QECH/EDE5/xiMc/8pWlr/EDlC/yHGjP8hSlL/ECkx/yHGjP8QGCH/EDEx/xg5Mf8YY1r/GDEp/xAQGP8QQkL/EDk5/xhSSv8Ya1r/GIRr/xiEa/8YjGv/GIRr/xhjWv8QMTn/EDE5/xh7Y/8QSkr/GK2E/xithP8Yc2P/ECkx/wgYGP8QKTH/GGNS/xAxOf8Yc2P/GK2E/xA5Of8YWlL/GFpS/xhjWv8YrXv/GJx7/xApMf8IIRj/AAAA/wgYEP8AAAD/CBgY/yFKQv8IGBj/AAgI/wAICP8QQkL/GKV7/wgpKf8YlHP/EEJC/xAIGP8YrYT/GFJS/xgYIf8YWlL/EEJC/wAAAP8IGBj/AAAI/xAQGP8hQjn/IUpC/xAhKf8QKTH/EBAY/xAhKf8AAAD/AAgI/wAAAP8ACAj/CCEY/xAhIf8QQkL/GGta/xAhIf8QECH/GEpK/xiMc/8YrYT/GIxz/xhaUv8QGCH/EEJC/xhrWv8YlHP/GEpK/xA5Qv8YhGv/GIxz/xhzY/8QMSn/ECkp/wAICP8ACAj/ECEh/xApIf8IGBD/KVJK/xgxKf8ACAj/CBAQ/xhaUv8QISn/GCkh/xBCQv8QEBj/EBgh/xhrWv8YOTn/GDk5/xAYIf8AGBj/AAAA/wghKf8hUkL/MWtj/zFjWv8hQjn/GDEp/xAxKf8IIRj/EDEp/wgYGP8ACAj/AAgI/xAQGP8QISn/EBgh/xhjWv8YWlL/GDkx/xApIf8YOTn/GDEp/wgYEP8QGCH/ECkx/xBCQv8YSkr/GFJK/xhKSv8Yc2P/GIRr/yHGjP8QISn/EDEx/xhzY/8YlHP/GJRz/xiMc/8Ya1r/ECkx/xAhIf8hOTn/IUpC/xAYGP8YKSH/EBAY/xApGP8YKSH/GCkh/wAACP8QEBj/MVpC/ylSOf8YECH/AAAI/xAhKf8pWlL/KVpS/ylaSv8pUkr/CBAY/wAIEP8AAAD/IUpC/xg5Mf8QGCH/GEpK/xiEa/8YrYT/IcaU/yHWlP8YnHv/GJRz/xiMa/8YlHP/GGNa/xAYKf8IEBD/ITkx/wghGP8YOTH/EBgh/xAxOf8QQkL/GFJS/xAQGP8YY1L/GIRr/wAIAP8hQjn/GJRz/xhSSv8Ya1r/ECkx/xAYKf8QKTH/EDk5/xA5Qv8QISn/ECkp/wgYGP8pSjn/GCkh/xApGP8QKRj/AAAI/ylKOf8xWkL/KVI5/xAQEP8IISH/CCkp/wghKf8IGCH/AAgQ/ylaSv8IGCH/IUI5/xgxKf8YOTH/ECEh/xAQGP8QKTH/EDE5/xAxOf8QKTH/EBgh/wAICP8Ye2v/EDE5/xA5Of8YpXv/IcaM/xiMc/8QMTn/CBgQ/yFKQv8hSkL/AAgA/xAQGP8QEBj/CBgY/xApMf8QECH/AAAA/xAQGP8h1pT/EBgh/xAQGP8YjHP/GKV7/xiUc/8YUkr/ECkx/xAQGP8pSkL/EBAY/ylKOf8YOSn/GDkp/yFKOf8hSjn/IUIp/yE5Kf8hOSn/ECkp/wgpKf8IISH/ABgY/wgYGP8QISH/GDEx/xAhIf8IGBD/AAAA/xg5Mf8YOTH/ECEh/xhCOf8IGBj/ECEh/yFKQv8YKSn/AAgI/xiUc/8QISn/MWta/xg5Mf8QGCH/EEJC/xhjUv8QOTn/IUI5/ylaUv8AAAD/AAAA/wAICP8IEBD/CBgQ/xApIf8IIRj/EDEp/xi1hP8QISn/AAAA/yG9jP8QISn/EEJC/xhzY/8YhGv/GIRr/xBKSv8QGCH/KVI5/xgxKf8QKRj/GDEp/yFKMf8YMSH/ITkp/wghIf8hSkL/MVpC/yFSQv8pUkr/IUpC/yFCQv8hQjn/CBgQ/wgICP8ICAj/IUpC/wAQEP8QGCH/EEJC/xhrWv8YlHP/GLWE/yHGjP8YhGv/GK2E/xh7Y/8Yc2P/ECkx/wgYGP8hSkL/GDkx/xg5Mf8hQjn/KVpS/wgQEP8AAAD/ABAQ/wAIAP8ACAj/ABAQ/wAICP8YOTH/EEJC/xAQGP8AAAD/Ic6U/xAhKf8IEBD/GKV7/xAxOf8YWlL/GGNS/xithP8pSjn/GDEp/wghGP8YQjH/KVI5/xgpIf8IGBj/KVpC/zlzUv8xY0r/OWNK/zFaQv8QISH/AAAA/wgYGP8AAAD/CBgY/xApIf8YOTH/AAAA/xAYKf8QOTn/EEpK/xBKSv8QQkL/EBgh/zlza/8YnHv/EBgp/xhzY/8hvYz/GKV7/xhaUv8QGCH/CBgY/xgxKf8xY1L/AAgI/wAAAP8IGBD/AAgI/xAhGP8AAAD/ABAQ/yFKQv8YOTH/CBgQ/wAQEP8Ye2P/ECEp/xApIf8YtYT/MWtj/xhzY/8QMTH/EBAh/ylSOf8pUjn/ECkY/xAhGP8YMSH/MWta/wAQEP8xc1L/MWNK/ylKOf8pSjH/ABAQ/wAQEP8ACCH/EBAQ/wAAAP8IGBj/KVJK/xgxKf8ACAj/AAgI/yFCOf8YMTH/ECkh/zFjUv8QISn/EDk5/xithP8QISn/GEI5/xg5Of8QMTn/GGNa/xhrWv8QKTH/ECkp/zFjUv8IIRj/AAAA/xApIf8QKSH/ECkh/wgYGP8AEAj/IUo5/xg5Of8QIRj/ECkh/xAQGP8QKSH/CCEY/xA5Of8pUkr/GGta/xBKSv8IGBj/KVI5/yFKMf8YMSH/MWNS/zFjUv8xa1r/ECkh/yljSv8pUkL/KVI5/yFCMf8ICBD/KVpS/wg5Sv8QKSH/ECkp/xg5Mf8pUkr/ABAQ/wgQEP8QGBj/EBAY/xBCQv8YjHP/IcaU/xithP8YSkr/GJx7/xhaUv8YrYT/EDE5/wAAAP8QISH/ECkp/wAQEP8QISH/KVJK/xgxKf8QKSH/GDkx/xAxKf8ACAj/AAgI/wAQEP8YOTH/IUI5/wAQEP8QMSn/AAgI/wAQEP8YMSn/CBAQ/yFCOf8QECH/EBgh/wAAAP8pUjn/OXNS/yFKMf8QMSH/ECEY/xApGP8QGBD/GDkp/xg5If8YOSn/MWNa/ylSSv8AEAj/EEox/xApIf8YMSn/GDkx/xg5Mf8QKSn/CBgQ/xApMf8Ya1r/GHNj/xBKSv8QGCH/ECkp/xAQGP8YnHv/IUI5/xBCQv8hvYz/GIRr/xAQGP8AAAD/AAAA/wgYEP8pWkr/IUo5/xApKf8hSkL/CBAQ/wAQEP8YOTH/IUI5/xg5Mf8xY1L/ECEY/xAhIf8QKSn/AAAA/wgYEP8QMSn/IUI5/xApKf8ACAD/AAAA/zFjQv85e1r/Qoxr/yFKOf8QKSH/IVI5/xg5Kf8QKRD/GBhC/yEYa/8xUlr/OXNK/wAYEP8IKTH/AAAI/xAhIf8YMSn/ECEh/wAIGP8AAAj/AAgI/wAAAP8pSkL/ECkx/xhzY/8YnHv/GHNj/xile/8YY1L/EDE5/yFKOf8YWlL/GIxz/xAxOf8AEBD/EDEp/yFCOf8YOTH/IUpC/xg5Mf8YOTH/KVJK/yFKQv8QKSn/CCEY/ylaUv8QMSn/ECEh/xgxMf8YOTH/AAgI/wAAAP8QKSH/GDEx/wAICP8IEBD/MWNC/zl7Wv9ChGP/IVI5/yFKOf8xa0r/MWtS/yFSMf8xOWP/OTGU/0Jjc/8xa0L/CDFC/wAYIf8hQjn/AAAA/wAYGP8IGDH/AAgQ/xAQGP8QKTH/GGta/xiUc/8YlHP/GGNS/xAYIf8QISn/GIRr/xAQIf8YrYT/GJRz/xAQIf8AAAD/ECEp/xAQGP8AAAD/AAAA/ylSQv8YOTH/ECkh/yFKQv8AAAD/ECkh/yFCOf8IGBD/KVJK/xApIf8YOTH/ECkp/xApIf8QKSn/AAgI/wgYGP8hOTn/GCkp/wgYGP85a1L/KVJC/zFjSv8pUjn/EDEh/yFSOf8pY0r/KWNC/ylrQv8xe0r/IUIx/whKOf8AGBD/GDkp/wAYEP8IKRj/ABAQ/xAxKf8IIRj/EBAY/xAQGP8IGBj/KVJC/xAYIf8QQkL/GGNa/xhrY/8YnHv/EDE5/xAQIf8QQkL/GJRz/xhjWv8QEBj/AAgI/wAICP8AAAD/GEI5/wgYEP8YQjn/IVJC/wAAAP8QKSn/KVpS/wghGP8YOTH/IUI5/wgYGP8hQjn/EDEp/wAIAP8IGBj/ECkh/xg5Mf8ICAj/ABAQ/zlzUv8YQjH/IUox/xg5Kf8QKRj/GDkp/yFSOf8pWkL/IVI5/ylSQv8YGEL/OWNj/yFKOf8AIRj/ABgQ/wAICP8AAAD/CBgY/wgYGP8QKSH/GDkx/xAQIf8QOUL/EFJK/xBKSv8QOUL/EDlC/xiMc/8QOTn/GHtr/xBCQv8AEBD/ECkx/xAxOf8ACAj/ABAQ/wgYGP8QISH/CBgQ/ylSSv8YOTH/AAgI/xAxKf8pWlL/CCEY/xApIf8pUkr/ABAQ/wgYGP8pWlL/ECEh/wAQEP8QMSn/CAgI/wAAAP8IGBj/KVpC/yFSOf8hUjn/OXta/0KEY/8xY0L/KTFK/xghQv8hQin/KVJC/0JSY/85Qnv/MUpS/wAAEP8ACAj/ABAQ/wAIAP8IGBj/GDEx/yFCOf8hUkL/EBAY/xA5Of8YY1r/GHNj/xhaUv8QMTn/GK2E/xhaUv8YY1L/EEpK/xA5Of8QEBj/ECEh/wAICP8AEBD/ECkh/wgYGP8IIRj/KVpS/wAQEP8AEBD/GDEp/zFrWv8YOTH/CBgY/ylSSv8IIRj/AAAA/xg5Of8pUkr/CBgY/wAQEP8IEBD/CBgY/xgxMf8pY0r/KVpC/ylSOf85c1L/OXta/ylaQv8xSlL/OUpa/zl7Uv8pWkL/OXtS/zlzUv8YQin/EDEY/xg5Kf8IGBj/CBAQ/xAhIf8hQjn/IUI5/xApKf8AAAD/ECkp/xApIf8AAAD/CCEY/xApIf8QISn/ECkh/xAxOf8YWlL/EDk5/xAQGP8AEBD/ABAI/wAICP8QISH/IUI5/xgxMf8YOTH/AAgA/wAAAP8IIRj/MWtj/yFKOf8AAAD/IUI5/wAAAP8AAAD/CBgQ/ylaUv8hQjn/ECEY/wAQEP8IIRj/GDkx/yFCMf8pWkL/MWtS/zFjSv8xY0r/KWNC/ylaOf8xY0r/OXNS/ylSOf8pWjn/IVIx/zljY/8pSkr/AAgI/xAhIf8IEBD/GDEx/xg5Mf8YOTH/ECkp/wAAAP8AAAj/AAAQ/xAhIf8hUkr/EDEp/xgxKf8YMSn/GDkx/xgxKf8QEBj/EBAY/yFCOf8hQjn/GEI5/xg5Mf8QISH/GDkx/wAQEP8AAAD/AAAA/wAAAP85c2P/IUpC/wAICP8YOTH/CBgQ/wghGP8QMSn/ECkh/zFjUv8hSjn/CBgY/xgxKf8YMSn/IUIp/ylSOf85a1L/OWtK/zFjSv8xY0r/MWNK/ylSOf8xWkL/OWtK/zFrQv8YISH/MTlr/zlaUv8AEBD/ABAI/wAICP8ACAj/AAgI/wAICP8IMSH/EEpC/wghOf8AAAj/KVpS/ylSSv8hQjn/ECkh/wgQEP8pUkr/ECkh/wghGP8YMTH/GDkx/wAQEP8AEAj/CBgY/wAQEP8hQjn/IUI5/xg5Mf8AEBD/CBAI/zFjWv8hSkL/CCEY/xgpKf8ACAD/CBAQ/xApIf8AAAD/GDkx/yFKQv8IGBD/IUI5/wgQEP8xUjn/IUIx/yFCMf85a1L/OWtK/zlrUv8xY0r/SoRj/0JzUv9Ce1L/Qmtr/yEhY/8hQkL/KWM5/wAAAP8AGBj/ACEY/wgxIf8IOSn/CEIp/whCKf8AEAj/IVJC/zFrWv8hQjn/IUpC/xg5Mf8YOTH/EDEp/xhCOf8ACAj/ECkp/xg5Mf8pUkr/CBgY/wAICP8QMSn/ECkp/xg5Mf8ACAj/CBgY/xAhIf8ACAj/KVJK/xhCMf8QKSn/CAgI/wAICP8IEBD/CCEY/wAQEP8AAAD/IUI5/xApKf8hQjn/ECkh/ylKMf8AGBD/ECkY/zFaQv8AAAD/MWNK/xhCMf8pWkL/OWtS/0KEWv9ShHv/Qlpr/yljQv8xY0r/IUox/yFKMf8ACAj/IUox/wgYGP8ACAj/MWta/zFjUv8AAAj/AAAI/xgxKf8YMSn/AAgI/wAAAP8hQjn/EDEp/wAICP8YOTH/GEI5/yFKQv8QISH/ABAQ/wgQEP8QKSH/GDEx/xgxKf8QKSH/CBgY/wAAAP8hQjn/CCEY/xAxKf8AAAD/AAAA/wAAAP8IIRj/GDEp/xAhGP8QKSH/IUo5/xgxMf8QMSn/ : 1 : 50 : 0 : 269;234;346;286
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 300
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
DELAY : 60
ENDIF
SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 14 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 5000
Keyboard : Down : KeyUp
SET CLIPBOARD : 16 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 13 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 5000
Keyboard : Down : KeyUp
SET CLIPBOARD : 14 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 12 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 5000
Keyboard : Down : KeyUp
SET CLIPBOARD : 13 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 11 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 5000
Keyboard : Down : KeyUp
SET CLIPBOARD : 12 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 10 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 5000
Keyboard : Down : KeyUp
SET CLIPBOARD : 11 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 9 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 1500
Keyboard : Left : KeyUp
SET CLIPBOARD : 15 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 8 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 1000
Keyboard : Left : KeyUp
SET CLIPBOARD : 9 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 7 : 0 : 0
Keyboard : Up : KeyDown
DELAY : 5000
Keyboard : Up : KeyUp
SET CLIPBOARD : 8 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 6 : 0 : 0
Keyboard : Up : KeyDown
Keyboard : Left : KeyDown
DELAY : 800
Keyboard : Left : KeyUp
Keyboard : Up : KeyUp
INCREMENT CLIPBOARD : 1
SET CLIPBOARD : 16 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 5 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 1100
Keyboard : Left : KeyUp
INCREMENT CLIPBOARD : 1
ENDIF
IF CLIPBOARD EQUALS : 4 : 0 : 0
Keyboard : Down : KeyDown
Keyboard : Left : KeyDown
DELAY : 800
Keyboard : Left : KeyUp
Keyboard : Down : KeyUp
INCREMENT CLIPBOARD : 1
ENDIF
IF CLIPBOARD EQUALS : 3 : 0 : 0
Keyboard : Down : KeyDown
Keyboard : Right : KeyDown
DELAY : 800
Keyboard : Right : KeyUp
Keyboard : Down : KeyUp
INCREMENT CLIPBOARD : 1
ENDIF
IF CLIPBOARD EQUALS : 2 : 0 : 0
Keyboard : Up : KeyDown
Keyboard : Right : KeyDown
DELAY : 800
Keyboard : Right : KeyUp
Keyboard : Up : KeyUp
INCREMENT CLIPBOARD : 1
ENDIF
IF CLIPBOARD EQUALS : 1 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 900
Keyboard : Right : KeyUp
INCREMENT CLIPBOARD : 1
ENDIF
GOTO : START-LAB
INCREMENT CLIPBOARD : 1
