SET CLIPBOARD : 1 : 0
LABEL : START-LAB
DELAY : 300
LABEL : Kill Pirate
IF IMAGE : Qk32CQAAAAAAADYAAAAoAAAAJwAAABAAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/zEpAP85KQD/MSkI/zEpCP8xIQj/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/zEhAP8AAAD/MSEA/ykhAP8AAAD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xKQD/OSkI/zEpCP8xIQj/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSkA/zEhAP8xKQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP85KQD/MSkA/zEpAP8xKQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8xIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAD//wAAAP8AAAD/AAAA/ykhAP8pIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAD//wAA//8AAP//AAAA/zEhAP8xIQD/AAAA/wAA//8AAP//AAD//wAA//8AAAD/KSEA/wAAAP8AAP//AAAA/wAA//8AAP//AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAAD/AAAA/wAAAP8pIQD/KSEA/ykhAP8AAAD/KSEA/wAAAP8AAAD/AAAA/ykhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSEA/zEhAP8xKQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/ : 1 : 90 : 0 : 138;163;746;476
DELAY : 50
Mouse : C-10 : C45 : Move : 0 : 0 : 0
Keyboard : A : KeyPress
DELAY : 50
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
Mouse : C15 : C25 : Move : 0 : 0 : 0
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
Keyboard : A : KeyPress
Mouse : C0 : C-20 : Move : 0 : 0 : 0
ENDIF
IF IMAGE : Qk32CQAAAAAAADYAAAAoAAAAJwAAABAAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/zEpAP85KQD/MSkI/zEpCP8xIQj/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/zEhAP8AAAD/MSEA/ykhAP8AAAD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xKQD/OSkI/zEpCP8xIQj/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSkA/zEhAP8xKQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP85KQD/MSkA/zEpAP8xKQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8xIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAD//wAAAP8AAAD/AAAA/ykhAP8pIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAD//wAA//8AAP//AAAA/zEhAP8xIQD/AAAA/wAA//8AAP//AAD//wAA//8AAAD/KSEA/wAAAP8AAP//AAAA/wAA//8AAP//AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAAD/AAAA/wAAAP8pIQD/KSEA/ykhAP8AAAD/KSEA/wAAAP8AAAD/AAAA/ykhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSEA/zEhAP8xKQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/ : 1 : 90 : 0 : 135;146;784;592
GOTO : Kill Pirate
ENDIF
LABEL : Check for Buoys
LABEL : Test for movement
IF CLIPBOARD EQUALS : 14 : 0 : 0
Mouse : 528 : 535 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 1 : 0
GOTO : Check for Buoys
ENDIF
IF CLIPBOARD EQUALS : 13 : 0 : 0
Mouse : 586 : 535 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 14 : 0
ENDIF
IF CLIPBOARD EQUALS : 12 : 0 : 0
Mouse : 507 : 535 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 13 : 0
ENDIF
IF CLIPBOARD EQUALS : 11 : 0 : 0
Mouse : 506 : 535 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 12 : 0
ENDIF
IF CLIPBOARD EQUALS : 10 : 0 : 0
Mouse : 506 : 535 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 11 : 0
ENDIF
IF CLIPBOARD EQUALS : 9 : 0 : 0
Mouse : 586 : 535 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 10 : 0
ENDIF
IF CLIPBOARD EQUALS : 8 : 0 : 0
Mouse : 586 : 535 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 9 : 0
ENDIF
IF CLIPBOARD EQUALS : 7 : 0 : 0
Mouse : 576 : 274 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1800
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 8 : 0
ENDIF
IF CLIPBOARD EQUALS : 6 : 0 : 0
Mouse : 576 : 274 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 7 : 0
ENDIF
IF CLIPBOARD EQUALS : 5 : 0 : 0
Mouse : 476 : 274 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 6 : 0
ENDIF
IF CLIPBOARD EQUALS : 4 : 0 : 0
Mouse : 511 : 274 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 5 : 0
ENDIF
IF CLIPBOARD EQUALS : 3 : 0 : 0
Mouse : 476 : 274 : Move : 0 : 0 : 0
Mouse : 0 : 0 : RightButtonDown : 0 : 1 : 0
DELAY : 1500
Mouse : 0 : 0 : RightButtonUp : 0 : 1 : 0
SET CLIPBOARD : 4 : 0
ENDIF
IF CLIPBOARD EQUALS : 2 : 0 : 0
REPEAT : 8 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Up : KeyPress
DELAY : 200
ENDREPEAT
REPEAT : 5 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Left : KeyPress
DELAY : 120
ENDREPEAT
SET CLIPBOARD : 3 : 0
ENDIF
IF CLIPBOARD EQUALS : 1 : 0 : 0
REPEAT : 8 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Up : KeyPress
DELAY : 120
ENDREPEAT
SET CLIPBOARD : 2 : 0
ENDIF
GOTO : START-LAB
