SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
COMMENT : Start at bottom buoy in valmond area, attack off
COMMENT : V2 - Reworking in 2018
COMMENT : V2b -make route wider
LABEL : START-LAB
DELAY : 300
LABEL : Kill Pirate
IF IMAGE : Qk32CQAAAAAAADYAAAAoAAAAJwAAABAAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/zEpAP85KQD/MSkI/zEpCP8xIQj/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/zEhAP8AAAD/MSEA/ykhAP8AAAD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xKQD/OSkI/zEpCP8xIQj/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSkA/zEhAP8xKQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP85KQD/MSkA/zEpAP8xKQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8xIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAD//wAAAP8AAAD/AAAA/ykhAP8pIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAD//wAA//8AAP//AAAA/zEhAP8xIQD/AAAA/wAA//8AAP//AAD//wAA//8AAAD/KSEA/wAAAP8AAP//AAAA/wAA//8AAP//AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAAD/AAAA/wAAAP8pIQD/KSEA/ykhAP8AAAD/KSEA/wAAAP8AAAD/AAAA/ykhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSEA/zEhAP8xKQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/ : 1 : 90 : 0 : 138;70;746;475
REPEAT : 5 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk32CQAAAAAAADYAAAAoAAAAJwAAABAAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/zEpAP85KQD/MSkI/zEpCP8xIQj/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/zEhAP8AAAD/MSEA/ykhAP8AAAD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xKQD/OSkI/zEpCP8xIQj/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSkA/zEhAP8xKQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP85KQD/MSkA/zEpAP8xKQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8xIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAD//wAAAP8AAAD/AAAA/ykhAP8pIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAD//wAA//8AAP//AAAA/zEhAP8xIQD/AAAA/wAA//8AAP//AAD//wAA//8AAAD/KSEA/wAAAP8AAP//AAAA/wAA//8AAP//AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAAD/AAAA/wAAAP8pIQD/KSEA/ykhAP8AAAD/KSEA/wAAAP8AAAD/AAAA/ykhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSEA/zEhAP8xKQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/ : 1 : 90 : 0 : 138;70;746;475
DELAY : 50
Mouse : C-10 : C45 : Move : 0 : 0 : 0
Keyboard : A : KeyPress
DELAY : 50
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C15 : C25 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Keyboard : A : KeyPress
Mouse : C0 : C-20 : Move : 0 : 0 : 0
DELAY : 1250
ENDIF
ENDREPEAT
ENDIF
COMMENT : Check if any left, fewer hits this time
IF IMAGE : Qk32CQAAAAAAADYAAAAoAAAAJwAAABAAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/zEpAP85KQD/MSkI/zEpCP8xIQj/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/zEhAP8AAAD/MSEA/ykhAP8AAAD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xKQD/OSkI/zEpCP8xIQj/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSkA/zEhAP8xKQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP85KQD/MSkA/zEpAP8xKQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8xIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAD//wAAAP8AAAD/AAAA/ykhAP8pIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAD//wAA//8AAP//AAAA/zEhAP8xIQD/AAAA/wAA//8AAP//AAD//wAA//8AAAD/KSEA/wAAAP8AAP//AAAA/wAA//8AAP//AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAAD/AAAA/wAAAP8pIQD/KSEA/ykhAP8AAAD/KSEA/wAAAP8AAAD/AAAA/ykhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSEA/zEhAP8xKQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/ : 1 : 90 : 0 : 138;150;746;450
REPEAT : 3 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk32CQAAAAAAADYAAAAoAAAAJwAAABAAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/zEpAP85KQD/MSkI/zEpCP8xIQj/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/zEhAP8AAAD/MSEA/ykhAP8AAAD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xKQD/OSkI/zEpCP8xIQj/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSkA/zEhAP8xKQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP85KQD/MSkA/zEpAP8xKQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8xIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAD//wAAAP8AAAD/AAAA/ykhAP8pIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAD//wAA//8AAP//AAAA/zEhAP8xIQD/AAAA/wAA//8AAP//AAD//wAA//8AAAD/KSEA/wAAAP8AAP//AAAA/wAA//8AAP//AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAAD/AAAA/wAAAP8pIQD/KSEA/ykhAP8AAAD/KSEA/wAAAP8AAAD/AAAA/ykhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSEA/zEhAP8xKQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/ : 1 : 90 : 0 : 138;150;746;450
DELAY : 50
Mouse : C-10 : C45 : Move : 0 : 0 : 0
Keyboard : A : KeyPress
DELAY : 50
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C15 : C25 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Keyboard : A : KeyPress
Mouse : C0 : C-20 : Move : 0 : 0 : 0
DELAY : 1250
ENDIF
ENDREPEAT
ENDIF
COMMENT : 3rd check
IF IMAGE : Qk32CQAAAAAAADYAAAAoAAAAJwAAABAAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/zEpAP85KQD/MSkI/zEpCP8xIQj/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/zEhAP8AAAD/MSEA/ykhAP8AAAD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xKQD/OSkI/zEpCP8xIQj/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSkA/zEhAP8xKQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP85KQD/MSkA/zEpAP8xKQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8xIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAD//wAAAP8AAAD/AAAA/ykhAP8pIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAD//wAA//8AAP//AAAA/zEhAP8xIQD/AAAA/wAA//8AAP//AAD//wAA//8AAAD/KSEA/wAAAP8AAP//AAAA/wAA//8AAP//AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAAD/AAAA/wAAAP8pIQD/KSEA/ykhAP8AAAD/KSEA/wAAAP8AAAD/AAAA/ykhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSEA/zEhAP8xKQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/ : 1 : 90 : 0 : 138;150;746;450
REPEAT : 3 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk32CQAAAAAAADYAAAAoAAAAJwAAABAAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/zEpAP85KQD/MSkI/zEpCP8xIQj/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/zEhAP8AAAD/MSEA/ykhAP8AAAD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xKQD/OSkI/zEpCP8xIQj/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSkA/zEhAP8xKQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP85KQD/MSkA/zEpAP8xKQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8pIQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8AAAD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/MSEA/ykhAP8xIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/wAAAP8AAP//AAAA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAAA/ykhAP8xKQD/KSEA/ykhAP8pIQD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/wAAAP8AAP//AAD//wAAAP8AAAD/AAAA/ykhAP8pIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAP//AAD//wAA//8AAP//AAAA/zEhAP8xIQD/AAAA/wAA//8AAP//AAD//wAA//8AAAD/KSEA/wAAAP8AAP//AAAA/wAA//8AAP//AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAA//8AAAD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAAAP8AAAD/AAD//wAAAP8AAAD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAAD/AAAA/wAAAP8pIQD/KSEA/ykhAP8AAAD/KSEA/wAAAP8AAAD/AAAA/ykhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/wAAAP8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAP//AAAA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSEA/zEhAP8xKQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8AAAD/AAD//wAA//8AAP//AAD//wAA//8AAAD/MSEA/zEhAP8AAAD/AAD//wAAAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xIQD/MSEA/zEhAP8xIQD/AAAA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/MSkA/zEpAP8xKQD/MSkA/zEpAP8xKQD/MSkA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/KSEA/ykhAP8pIQD/ : 1 : 90 : 0 : 138;150;746;450
DELAY : 50
Mouse : C-10 : C45 : Move : 0 : 0 : 0
Keyboard : A : KeyPress
DELAY : 50
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C15 : C25 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Keyboard : A : KeyPress
Mouse : C0 : C-20 : Move : 0 : 0 : 0
DELAY : 1250
ENDIF
ENDREPEAT
ENDIF
LABEL : Check for Buoys
LABEL : Test for movement
IF CLIPBOARD EQUALS : 15 : 0 : 0
SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 14 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 100
Keyboard : Left : KeyDown
DELAY : 100
DELAY : 1350
Keyboard : Down : KeyUp
DELAY : 100
Keyboard : Left : KeyUp
DELAY : 100
ENDIF
IF CLIPBOARD EQUALS : 13 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 100
Keyboard : Right : KeyDown
DELAY : 100
DELAY : 1200
Keyboard : Down : KeyUp
DELAY : 100
Keyboard : Right : KeyUp
DELAY : 100
ENDIF
IF CLIPBOARD EQUALS : 12 : 0 : 0
REPEAT : 8 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Down : KeyPress
DELAY : 200
ENDREPEAT
REPEAT : 4 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Right : KeyPress
DELAY : 200
ENDREPEAT
ENDIF
IF CLIPBOARD EQUALS : 11 : 0 : 0
REPEAT : 9 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Down : KeyPress
DELAY : 180
ENDREPEAT
ENDIF
IF CLIPBOARD EQUALS : 10 : 0 : 0
REPEAT : 6 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Down : KeyPress
DELAY : 180
ENDREPEAT
ENDIF
IF CLIPBOARD EQUALS : 9 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 100
Keyboard : Right : KeyDown
DELAY : 100
DELAY : 1200
Keyboard : Down : KeyUp
DELAY : 100
Keyboard : Right : KeyUp
DELAY : 100
ENDIF
IF CLIPBOARD EQUALS : 8 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 100
Keyboard : Right : KeyDown
DELAY : 100
DELAY : 1200
Keyboard : Down : KeyUp
DELAY : 100
Keyboard : Right : KeyUp
DELAY : 100
ENDIF
IF CLIPBOARD EQUALS : 7 : 0 : 0
REPEAT : 10 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Up : KeyPress
DELAY : 180
ENDREPEAT
ENDIF
IF CLIPBOARD EQUALS : 6 : 0 : 0
REPEAT : 10 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Up : KeyPress
DELAY : 180
ENDREPEAT
ENDIF
IF CLIPBOARD EQUALS : 5 : 0 : 0
REPEAT : 9 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Up : KeyPress
DELAY : 180
ENDREPEAT
ENDIF
IF CLIPBOARD EQUALS : 4 : 0 : 0
Keyboard : Up : KeyDown
DELAY : 100
Keyboard : Left : KeyDown
DELAY : 100
DELAY : 1200
Keyboard : Up : KeyUp
DELAY : 100
Keyboard : Left : KeyUp
DELAY : 100
ENDIF
IF CLIPBOARD EQUALS : 3 : 0 : 0
Keyboard : Up : KeyDown
DELAY : 100
Keyboard : Left : KeyDown
DELAY : 100
DELAY : 1200
Keyboard : Up : KeyUp
DELAY : 100
Keyboard : Left : KeyUp
DELAY : 100
ENDIF
IF CLIPBOARD EQUALS : 2 : 0 : 0
REPEAT : 8 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Up : KeyPress
DELAY : 200
ENDREPEAT
REPEAT : 5 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Left : KeyPress
DELAY : 200
ENDREPEAT
ENDIF
IF CLIPBOARD EQUALS : 1 : 0 : 0
REPEAT : 6 : 0 : 0 : Enter the number of iterations: : 0 : 0
Keyboard : Up : KeyPress
DELAY : 180
ENDREPEAT
ENDIF
INCREMENT CLIPBOARD : 1
GOTO : START-LAB
