SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
LABEL : START-LAB
DELAY : 100
LABEL : Kill Bar - top
Keyboard : F4 : KeyPress
DELAY : 100
Keyboard : F5 : KeyPress
DELAY : 100
Keyboard : F2 : KeyPress
DELAY : 100
REPEAT : 3 : 0 : 0 : Enter the number of iterations: : 0 : 0
DELAY : 100
Keyboard : F1 : KeyPress
DELAY : 100
IF IMAGE : Qk2uAAAAAAAAADYAAAAoAAAACgAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABgA/wAYAP8AIQD/ACkA/wApAP8AKQD/ACkA/wApAP8AKQD/ACkA/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AIQD/ACEA/wAYAP8AIQD/ABgA/wAYAP8AEAD/ACEA/wAhAP8AKQD/ : 1 : 90 : 0 : 570;297;315;149
SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C7 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 7000
ENDIF
IF IMAGE : Qk2uAAAAAAAAADYAAAAoAAAACgAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABgA/wAYAP8AIQD/ACkA/wApAP8AKQD/ACkA/wApAP8AKQD/ACkA/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AIQD/ACEA/wAYAP8AIQD/ABgA/wAYAP8AEAD/ACEA/wAhAP8AKQD/ : 1 : 90 : 0 : 570;297;315;143
SET CLIPBOARD : 2 : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C7 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 6000
ENDIF
IF IMAGE : Qk0SAQAAAAAAADYAAAAoAAAACwAAAAUAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAa4yE/4S1rf+EtaX/hJyM/1prY/9jc2v/hKWU/3ucjP97nIz/jK2c/4ytnP9zlIz/e5yM/3utpf9zlIz/MTk5/1prY/+MrZz/pda9/5S1pf+cva3/e5yM/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/e5yU/3OMe/9re3P/a3tz/2N7c/9aa2P/c4yE/2uMe/9zjIT/e5yU/3uclP8hKSH/ISkh/ykxKf8YISH/CBAQ/wgQEP8IEAj/AAgI/wAIAP8AAAD/EBgQ/w== : 1 : 90 : 0 : 569;324;112;128
SET CLIPBOARD : 3 : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C8 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 7000
ENDIF
LABEL : Kill Bar - top2
IF IMAGE : Qk3GAQAAAAAAADYAAAAoAAAAMgAAAAIAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAASmNj/0pjWv9KY1r/MVpS/0JaWv9SY2P/SmNj/1JrY/85UlL/QlpS/1JjWv9KY1r/KUpS/ylKSv8xUkr/KUJC/yFKQv8pWlL/KWtj/ylza/85Y1r/WnNr/2Nza/9aa2P/UmNa/zFKQv8xSkL/OVJK/0JaUv8xUkr/IUpC/ylKQv8xSkL/MUpC/ylCMf8QMSH/EDEx/ylKQv9CY1r/SmNj/0pjWv9KY1r/MVpS/0JaWv9SY2P/SmNj/1JrY/8xUlL/QlJS/1JjUv8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 557;293;329;208
SET CLIPBOARD : 4 : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C8 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 6000
ENDIF
IF IMAGE : Qk3GAQAAAAAAADYAAAAoAAAAMgAAAAIAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAASmNj/0pjWv9KY1r/MVpS/0JaWv9SY2P/SmNj/1JrY/85UlL/QlpS/1JjWv9KY1r/KUpS/ylKSv8xUkr/KUJC/yFKQv8pWlL/KWtj/ylza/85Y1r/WnNr/2Nza/9aa2P/UmNa/zFKQv8xSkL/OVJK/0JaUv8xUkr/IUpC/ylKQv8xSkL/MUpC/ylCMf8QMSH/EDEx/ylKQv9CY1r/SmNj/0pjWv9KY1r/MVpS/0JaWv9SY2P/SmNj/1JrY/8xUlL/QlJS/1JjUv8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 681;487;83;95
SET CLIPBOARD : 5 : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C8 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 6000
ENDIF
IF IMAGE : Qk3GAQAAAAAAADYAAAAoAAAAMgAAAAIAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAASmNj/0pjWv9KY1r/MVpS/0JaWv9SY2P/SmNj/1JrY/85UlL/QlpS/1JjWv9KY1r/KUpS/ylKSv8xUkr/KUJC/yFKQv8pWlL/KWtj/ylza/85Y1r/WnNr/2Nza/9aa2P/UmNa/zFKQv8xSkL/OVJK/0JaUv8xUkr/IUpC/ylKQv8xSkL/MUpC/ylCMf8QMSH/EDEx/ylKQv9CY1r/SmNj/0pjWv9KY1r/MVpS/0JaWv9SY2P/SmNj/1JrY/8xUlL/QlJS/1JjUv8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 557;293;329;208
SET CLIPBOARD : 6 : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C7 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 6000
ENDIF
ENDREPEAT
DELAY : 250
LABEL : Kill Bar- btm
REPEAT : 6 : 0 : 0 : Enter the number of iterations: : 0 : 0
DELAY : 100
Keyboard : F1 : KeyPress
DELAY : 100
IF IMAGE : Qk2KAAAAAAAAADYAAAAoAAAAFQAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/ : 1 : 90 : 0 : 293;464;131;132
SET CLIPBOARD : 11 : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C10 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 8000
ENDIF
DELAY : 150
IF IMAGE : Qk0eAQAAAAAAADYAAAAoAAAAHQAAAAIAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8xWlL/SmNa/1JjUv9CUkr/OUpC/0JSSv9SWlL/UmNS/0JaSv8hUkr/IWtj/ylza/8pc2v/KYRz/yl7a/8hY1L/IUpC/0pjWv9Ka2P/OWtj/zFrY/8xY2P/MWNa/zFjWv85Y1r/OWNa/zFaUv8xUkr/Smtj/w== : 1 : 90 : 0 : 313;505;207;141
SET CLIPBOARD : 13 : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C10 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 6000
ENDIF
LABEL : Kill Bar- btm3
IF IMAGE : Qk2KAAAAAAAAADYAAAAoAAAABwAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAA/wAQAP8AEAD/ACEA/wAYAP8AGAD/ABAA/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AEAD/ABAA/wAQAP8AEAD/AAgA/wAQAP8AEAD/ : 1 : 90 : 0 : 321;460;125;130
SET CLIPBOARD : 16 : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C15 : C50 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 4000
ENDIF
ENDREPEAT
IF IMAGE : Qk1yAAAAAAAAADYAAAAoAAAABQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAgA/wAIAP8ACAD/ABAA/wAIAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAYAP8AEAD/ABAA/wAYAP8AGAD/ : 1 : 91 : 0 : 692;470;70;42
SET CLIPBOARD : 17 : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C15 : C50 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 4000
ENDIF
LABEL : Check-reds
DELAY : 100
Keyboard : F1 : KeyPress
DELAY : 100
REPEAT : 3 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 355;439;167;210
SET CLIPBOARD : 21a : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C0 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 5000
ENDIF
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 355;439;167;210
SET CLIPBOARD : 22a : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C0 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 5000
ENDIF
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 524;295;349;193
SET CLIPBOARD : 23a : 0 : Please enter the text to store in clipboard:
DELAY : 25
Mouse : C0 : C35 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 6000
ENDIF
ENDREPEAT
LABEL : Specific locations
DELAY : 100
Keyboard : F1 : KeyPress
DELAY : 100
SET CLIPBOARD : Specific : 0 : Please enter the text to store in clipboard:
REPEAT : 1 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk22CwAAAAAAADYAAAAoAAAALgAAABAAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAgI/wAICP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AGP//ABj//wAY//8AAAj/AAAI/wAY//8ACAj/AAgI/wAACP8AAAj/ABj//wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAICP8ACAj/AAgI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8AGP//AAgI/wAICP8ACAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/ABj//wAACP8ACAj/AAgI/wAICP8AAAj/Qvf//wAAAP8AAAD/AAAA/wAACP9C9///AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAICP8AGP//ABj//wAACP8AAAj/AAgI/wAY//8AAAj/AAAI/wAACP8AAAj/ABj//wAACP8AAAj/ABj//wAY//8ACAj/AAgI/wAACP8AGP//ABj//wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/ABj//wAY//8AGP//AAgI/wAY//8ACAj/AAAI/wAACP8AAAj/ABj//wAY//8AGP//ABj//wAACP8AAAj/AAAI/wAY//8AAAj/ABj//wAY//8AGP//AAAI/wAACP8AGP//ABj//wAY//8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AGP//AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8ACAj/AAAI/wAICP9C9///AAgI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/ABj//wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/Qvf//0L3//9C9///Qvf//wAACP8AAAj/AAAI/0L3//9C9///Qvf//wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAICP8ACAj/AAAI/wAY//8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//0L3//9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP9C9///Qvf//0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AGP//ABj//wAY//8ACAj/ABj//wAACP8AAAj/AAAI/wAY//8AGP//ABj//wAY//8AAAj/ABj//wAACP8AAAj/ABj//wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8ACAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/Qvf//wAICP8ACAj/AAgI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8ACAj/ABj//wAY//8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/ABj//wAY//8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/ABj//wAICP8ACAj/AAgI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAICP9C9///AAgI/wAICP8ACAj/AAAI/0L3//8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAACP8AGP//AAgI/wAACP8AGP//AAAI/wAACP8ACAj/AAAI/wAACP8AGP//AAgI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAY//8ACAj/AAAI/wAICP8ACAj/ABj//wAICP8AAAj/AAAI/wAACP8ACAj/Qvf//wAICP8ACAj/AAgI/wAICP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/ABj//wAACP8AAAj/AAAI/wAACP8AAAj/ABj//wAACP8ACAj/ABj//wAACP8AAAj/AAgI/wAICP8ACAj/ABj//wAICP8AAAj/ABj//wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8ACAj/AAgI/wAY//8ACAj/AAAI/wAACP8AAAj/AAAI/0L3//8ACAj/AAgI/wAICP8ACAj/Qvf//wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAY//8AAAj/AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AGP//ABj//wAY//8AAAj/AAAI/wAY//8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/ABj//wAACP8AAAj/AAAI/wAICP8AGP//AAAI/w== : 0 : 30 : 0 : 426;386;51;45
DELAY : 25
Mouse : 434 : 441 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 4500
ENDIF
IF IMAGE : Qk0GEAAAAAAAADYAAAAoAAAALAAAABcAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/ABj//wAACP8AAAj/AAgI/wAY//8AGP//AAAI/wAACP8ACAj/ABj//wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8AGP//ABj//wAICP8ACAj/AAAI/wAY//8AGP//AAAI/wAACP8AAAj/ABj//wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8ACAj/ABj//wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/ABj//wAY//8AGP//AAgI/wAY//8ACAj/AAAI/wAACP8AAAj/ABj//wAY//8AGP//ABj//wAACP8AAAj/AAAI/wAY//8AAAj/ABj//wAY//8AGP//AAAI/wAACP8AGP//ABj//wAY//8ACAj/AAgI/wAACP8AAAj/AAAI/wAY//8AGP//ABj//wAY//8ACAj/AAAI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/ABj//wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AGP//AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAICP8ACAj/AAAI/wAY//8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAICP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAY//8AGP//ABj//wAICP8AGP//AAAI/wAACP8AAAj/ABj//wAY//8AGP//ABj//wAACP8AGP//AAAI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAICP8AAAj/ABj//wAACP8AAAj/AAAI/wAY//8AGP//ABj//wAY//8AAAj/ABj//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8ACAj/ABj//wAY//8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/ABj//wAY//8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/ABj//wAICP8ACAj/AAgI/wAACP8AGP//AAAI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAY//8AGP//AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/ABj//wAACP8AAAj/AAAI/wAACP8AAAj/ABj//wAICP8AAAj/ABj//wAACP8AAAj/AAgI/wAACP8AAAj/ABj//wAICP8AAAj/ABj//wAACP8AAAj/AAAI/wAACP8AGP//AAgI/wAACP8ACAj/AAgI/wAY//8ACAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAICP8AGP//AAAI/wAACP8ACAj/AAgI/wAICP8AGP//AAgI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAICP8ACAj/ABj//wAICP8AAAj/ABj//wAACP8AAAj/AAAI/wAACP8AAAD/ABj//wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAY//8AAAj/AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AGP//ABj//wAY//8AAAj/AAAI/wAY//8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/ABj//wAACP8AAAj/AAAI/wAICP8AGP//AAAI/wAACP8AAAj/ABj//wAY//8AGP//AAAI/wAACP8AGP//AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/ABj//wAACP8AAAj/AAgI/wAICP8ACAj/ABj//wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAY//8AGP//ABj//wAACP8AAAj/ABj//wAACP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AGP//ABj//wAY//8ACAj/AAAI/wAICP8ACAj/AAgI/wAICP8AGP//AAAI/wAACP8ACAj/AAgI/wAICP8AGP//AAAI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAACP8AGP//AAAA/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAY//8ACAj/AAAI/wAACP8AAAj/ABj//wAACP8AAAj/ABj//wAICP8ACAj/AAAI/wAACP8AAAj/ABj//wAICP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8AGP//AAAI/wAICP8ACAj/ABj//wAY//8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAY//8AGP//AAAI/wAACP8AAAj/ABj//wAY//8AAAj/AAAI/wAICP8AGP//AAAI/wAACP8AAAj/ABj//wAICP8AAAj/AAAI/wAACP8AGP//AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AGP//ABj//wAY//8AAAj/ABj//wAACP8AAAj/AAgI/wAACP8AGP//ABj//wAY//8AGP//AAAI/wAAAP8AAAj/ABj//wAACP8AGP//ABj//wAY//8AAAj/AAAI/wAY//8AGP//ABj//wAACP8AAAj/AAAI/wAACP8AAAj/ABj//wAY//8AGP//ABj//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AGP//AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAY//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/ABj//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAD/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAY//8AGP//ABj//wAY//8ACAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/w== : 0 : 30 : 0 : 463;390;43;37
DELAY : 25
Mouse : 475 : 415 : Move : 0 : 0 : 0
DELAY : 99
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 4500
ENDIF
ENDREPEAT
GOTO : START-LAB
