SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
COMMENT : V3 - Based on bandits 3E
LABEL : START-LAB
DELAY : 100
LABEL : Kill Bar - top
Keyboard : F5 : KeyPress
DELAY : 125
Keyboard : F4 : KeyPress
DELAY : 75
Keyboard : F2 : KeyPress
DELAY : 75
DELAY : 50
Keyboard : F1 : KeyPress
DELAY : 100
REPEAT : 2 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 39;50;771;518
DELAY : 25
Mouse : C12 : C30 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 3000
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 377;238;434;284
COMMENT : V3 - Tweak to targetting
DELAY : 50
Mouse : C16 : C30 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 3500
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 3;244;791;290
COMMENT : V3 - Tweak to targetting
DELAY : 50
Mouse : C13 : C30 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C10 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 3500
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 220;232;445;272
COMMENT : V3E - New - check middle more.
DELAY : 50
Mouse : C16 : C30 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C10 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 3500
ENDIF
LABEL : Finish-Off
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 350;254;207;234
DELAY : 50
Mouse : C5 : C35 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 270;203;343;306
DELAY : 50
Mouse : C3 : C40 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk0uEAAAAAAAADYAAAAoAAAASQAAAA4AAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8IGBj/EDFC/xhKWv8hWnP/IVpz/xhKWv8QMUL/CBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAQEP8YSlL/MWuE/0qctf+Ezuf/lN7v/5Te7/+Ezuf/UqW9/yljc/8YQlL/AAgQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wgYIf8xa4T/UqW9/2u1xv85Y2v/GCkx/wAAAP8AAAD/ITEx/0pze/+U1uf/SqW1/yFSa/8IEBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wgQEP85hJz/UqW9/0qElP8IGBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/EBgh/3Oltf9rvc7/IVJr/wAIEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xc4T/SqW1/zFjc/8AAAD/AAAA/wAAAP8AAAj/AABj/wAAUv8AAAD/AAAA/wAAAP8AAAD/Y5Sl/1qtxv8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/UqW9/zl7lP8AAAD/AAAA/wAAAP8AABj/AACU/wAApf8AAJT/AABr/wAACP8AAAD/AAAA/wAICP+U1uf/lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/0qctf8YMUL/AAAA/wAAAP8AABD/AAC1/wAAzv8AAM7/AAC1/wAAnP8AAHP/AAAI/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP85e5T/CBAY/wAAAP8AAAD/AAC1/wAA3v8AAO//AADv/wAA5/8AAL3/AACc/wAAa/8AAAD/AAAA/wAAAP8AAAD/AABr/wAAxv8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/KWuE/wAAAP8AAAD/AABr/wAA7/8AAPf/AAD//wAA//8AAPf/AADn/wAAvf8AAJz/AAAx/wAAAP8AAAD/AAAA/0pK1v+UlO//AADO/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/ylre/8AAAD/AAAA/wAA5/8AAP//AAD//wAA//8AAP//AAD//wAA9/8AAN7/AACt/wAAe/8AAAD/AAAA/wAAAP9KSt7/1tb3/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/8xc4z/ABAQ/wgIIf85Of//ISH//xAQ//8ICP//CAj//wgI//8AAP//AADv/wAAzv8AAKX/AAAI/wAAAP8AAAD/AABr/0pK5/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//QpSt/xApMf8ICCH/c3P//2Nj//9CQv//MTH//zk5//9CQv//OTn//xgY//8AAOf/AADG/wAAEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/3PG1v8hUmv/AAAA/4yMzv+lpf//jIz//3Nz//+EhP//lJT//5SU//9ra///GBj//wAAxv8AAAD/IVJr/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8= : 0 : 30 : 1 : 813;396;164;244
COMMENT : Test life, pot, clear middle a little more
Keyboard : F3 : KeyPress
DELAY : 250
ENDIF
COMMENT : Check if out of ammo
IF IMAGE : Qk1aGAAAAAAAADYAAAAoAAAAZwAAAA8AAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////3v///97////e////wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///97////e////3v///8ACAj/e////wAACP8AAAj/e////3v///97////AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////e////3v///8AAAj/AAAI/wAICP8AAAj/AAAI/3v///8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/e////wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAD/AAAI/3v///8AAAj/AAgI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAICP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/e////wAACP8AAAj/AAgI/wAICP97////e////3v///8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////3v///8AAAj/AAAA/3v///8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8ACAj/AAAI/wAACP97////AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAD/AAAI/wAACP97////AAgI/wAICP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAgI/3v///8AAAj/AAAI/wAACP97////AAAI/wAAAP8AAAD/e////wAACP8AAAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAgI/wAICP97////AAgI/wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAgI/wAACP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAICP8ACAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAD/AAAI/wAACP97////AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAgI/wAICP8ACAj/e////wAICP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8ACAj/AAgI/wAACP97////AAAI/wAACP97////AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAA/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////3v///97////e////3v///97////e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAICP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAgI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP97////AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAICP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/e////wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAAAP8AAAj/AAAI/wAICP97////AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAAAP97////e////wAACP8AAAj/AAAI/3v///97////AAAI/wAACP8AAAj/e////wAACP8AAAj/e////3v///8AAAj/AAAI/wAACP97////e////wAICP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAAAP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAgI/wAICP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/3v///97////e////3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///97////e////wAACP8AAAj/AAAI/wAACP97////e////3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP97////e////3v///8ACAj/AAgI/3v///97////e////wAACP8AAAj/AAAI/3v///8AAAj/e////3v///97////AAAI/wAICP97////e////3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///97////e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/3v///8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP97////AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP97////e////3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/ : 0 : 30 : 0 : 333;875;771;102
PLAY MACRO : C:\Macros\logout.mcr
DELAY : 28842000
ENDIF
PLAY MACRO : C:\Macros\Hunting\test-dead.mcr
ENDREPEAT
LABEL : Test for movement
IF CLIPBOARD EQUALS : 5 : 0 : 0
SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 4 : 0 : 0
Keyboard : Up : KeyDown
DELAY : 2500
Keyboard : Up : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 3 : 0 : 0
Keyboard : Up : KeyDown
DELAY : 3000
Keyboard : Up : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 2 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 2500
Keyboard : Down : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 1 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 3000
Keyboard : Down : KeyUp
ENDIF
INCREMENT CLIPBOARD : 1
GOTO : START-LAB
