SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
COMMENT : Start bottom right corner
COMMENT : F1=regen, F2=WWT, F3=GFP, F4=Crate, F5=Warr totem
LABEL : START-LAB
DELAY : 100
LABEL : Kill Bar - top
Keyboard : F2 : KeyPress
DELAY : 100
Keyboard : F1 : KeyPress
DELAY : 100
REPEAT : 1 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 14;52;767;483
COMMENT : Middle
DELAY : 25
Mouse : C13 : C30 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 5;117;786;397
COMMENT : Left
DELAY : 50
Mouse : C13 : C25 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 7;218;785;379
COMMENT : Bottom
DELAY : 50
Mouse : C13 : C25 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 185;140;438;342
COMMENT : Middle
DELAY : 25
Mouse : C16 : C28 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 350;254;207;234
COMMENT : Red
DELAY : 50
Mouse : C8 : C25 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 1000
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 174;51;451;542
COMMENT : middle vert
DELAY : 50
Mouse : C15 : C30 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C10 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk0eCQAAAAAAADYAAAAoAAAAOQAAAAoAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/////////////////wAACP8AAAD/AAAA//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI//////8AAAj/////////////////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/////////////////AAAI/wAACP8AAAj/AAAI//////8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/////////////////wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj//////wAICP8AAAj/AAAI//////8AAAD/AAAA/wAAAP//////AAAI/wAACP8AAAj//////wAACP8ACAj/AAgI////////////AAAI/wAACP8AAAj//////wAACP8AAAj/AAgI/wAACP//////AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP//////AAAI/wAICP//////AAgI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj//////wAACP//////AAAI/wAICP8ACAj/AAgI//////8AAAj/AAAI/wAACP8AAAD/AAAI//////8ACAj/AAgI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI//////8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAICP//////AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP//////AAAI/wAICP8ACAj/AAgI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8ACAj/AAgI//////8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI//////8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////////////////////////////////////AAAI/wAACP8AAAD/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8ACAj/AAAI/wAACP8AAAj/AAAI//////8ACAj/AAgI//////////////////////////////////////8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////////////////////////////////////AAgI/wAACP//////AAAI/wAACP//////AAgI/wAACP8ACAj/AAAI/wAACP//////AAAI/wAACP8AAAj//////wAACP//////AAAI/wAACP8AAAj/AAAI//////8ACAj/AAgI/wAICP8AAAj/AAAI//////8ACAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAgI/wAICP//////AAgI/wAICP//////AAgI/wAICP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj//////wAACP//////AAAI/wAACP8ACAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI//////8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP//////AAgI/wAICP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAgI/wAICP8ACAj//////wAICP8AAAj/AAAI//////8AAAj/AAAI/wAICP//////AAAI/wAACP8AAAj//////wAACP8ACAj/AAAI////////////AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj//////wAICP8AAAj/AAAI////////////AAgI/wAACP8AAAD/AAAI/wAACP//////AAgI/wAICP8ACAj//////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP//////AAgI/wAACP8AAAj/AAAI/////////////////wAACP8AAAj/AAAI//////8ACAj/AAgI/wAACP8AAAj/AAAI//////8AAAj/AAgI//////8AAAj/////////////////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/////////////////AAAI/wAACP8AAAj/AAAI//////8AAAj/////////////////AAAI/wAACP//////AAAI/wAICP8ACAj/AAAI/////////////////wAACP8AAAj/AAAI/wAACP////// : 0 : 30 : 0 : 5;756;248;51
COMMENT : Check if still targetting and delay moving off
Keyboard : F12 : KeyPress
DELAY : 2500
ENDIF
LABEL : Finish-Off
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 350;254;207;234
DELAY : 50
Mouse : C13 : C35 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
GOTO : Skip-targetting
LABEL : Skip-targetting
IF IMAGE : Qk0uEAAAAAAAADYAAAAoAAAASQAAAA4AAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8IGBj/EDFC/xhKWv8hWnP/IVpz/xhKWv8QMUL/CBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAQEP8YSlL/MWuE/0qctf+Ezuf/lN7v/5Te7/+Ezuf/UqW9/yljc/8YQlL/AAgQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wgYIf8xa4T/UqW9/2u1xv85Y2v/GCkx/wAAAP8AAAD/ITEx/0pze/+U1uf/SqW1/yFSa/8IEBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wgQEP85hJz/UqW9/0qElP8IGBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/EBgh/3Oltf9rvc7/IVJr/wAIEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xc4T/SqW1/zFjc/8AAAD/AAAA/wAAAP8AAAj/AABj/wAAUv8AAAD/AAAA/wAAAP8AAAD/Y5Sl/1qtxv8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/UqW9/zl7lP8AAAD/AAAA/wAAAP8AABj/AACU/wAApf8AAJT/AABr/wAACP8AAAD/AAAA/wAICP+U1uf/lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/0qctf8YMUL/AAAA/wAAAP8AABD/AAC1/wAAzv8AAM7/AAC1/wAAnP8AAHP/AAAI/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP85e5T/CBAY/wAAAP8AAAD/AAC1/wAA3v8AAO//AADv/wAA5/8AAL3/AACc/wAAa/8AAAD/AAAA/wAAAP8AAAD/AABr/wAAxv8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/KWuE/wAAAP8AAAD/AABr/wAA7/8AAPf/AAD//wAA//8AAPf/AADn/wAAvf8AAJz/AAAx/wAAAP8AAAD/AAAA/0pK1v+UlO//AADO/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/ylre/8AAAD/AAAA/wAA5/8AAP//AAD//wAA//8AAP//AAD//wAA9/8AAN7/AACt/wAAe/8AAAD/AAAA/wAAAP9KSt7/1tb3/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/8xc4z/ABAQ/wgIIf85Of//ISH//xAQ//8ICP//CAj//wgI//8AAP//AADv/wAAzv8AAKX/AAAI/wAAAP8AAAD/AABr/0pK5/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//QpSt/xApMf8ICCH/c3P//2Nj//9CQv//MTH//zk5//9CQv//OTn//xgY//8AAOf/AADG/wAAEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/3PG1v8hUmv/AAAA/4yMzv+lpf//jIz//3Nz//+EhP//lJT//5SU//9ra///GBj//wAAxv8AAAD/IVJr/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8= : 0 : 30 : 1 : 813;396;164;244
COMMENT : Test life, pot, clear middle a little more
Keyboard : F3 : KeyPress
DELAY : 250
ENDIF
COMMENT : Check if out of ammo
IF IMAGE : Qk1aGAAAAAAAADYAAAAoAAAAZwAAAA8AAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////3v///97////e////wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///97////e////3v///8ACAj/e////wAACP8AAAj/e////3v///97////AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////e////3v///8AAAj/AAAI/wAICP8AAAj/AAAI/3v///8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/e////wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAD/AAAI/3v///8AAAj/AAgI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAICP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/e////wAACP8AAAj/AAgI/wAICP97////e////3v///8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////3v///8AAAj/AAAA/3v///8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8ACAj/AAAI/wAACP97////AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAD/AAAI/wAACP97////AAgI/wAICP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAgI/3v///8AAAj/AAAI/wAACP97////AAAI/wAAAP8AAAD/e////wAACP8AAAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAgI/wAICP97////AAgI/wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAgI/wAACP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAICP8ACAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAD/AAAI/wAACP97////AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAgI/wAICP8ACAj/e////wAICP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8ACAj/AAgI/wAACP97////AAAI/wAACP97////AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAA/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////3v///97////e////3v///97////e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAICP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAgI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP97////AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAICP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/e////wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAAAP8AAAj/AAAI/wAICP97////AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAAAP97////e////wAACP8AAAj/AAAI/3v///97////AAAI/wAACP8AAAj/e////wAACP8AAAj/e////3v///8AAAj/AAAI/wAACP97////e////wAICP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAAAP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAgI/wAICP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/3v///97////e////3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///97////e////wAACP8AAAj/AAAI/wAACP97////e////3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP97////e////3v///8ACAj/AAgI/3v///97////e////wAACP8AAAj/AAAI/3v///8AAAj/e////3v///97////AAAI/wAICP97////e////3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///97////e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/3v///8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP97////AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP97////e////3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/ : 0 : 30 : 0 : 333;875;771;102
PLAY MACRO : C:\Macros\logout.mcr
DELAY : 28842000
ENDIF
PLAY MACRO : C:\Macros\Hunting\test-dead.mcr
ENDREPEAT
IF CLIPBOARD EQUALS : 11 : 0 : 0
COMMENT : Restart circuit and do stuff that happens once a loop
Keyboard : F5 : KeyPress
DELAY : 125
Keyboard : F4 : KeyPress
DELAY : 100
SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 10 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 100
Keyboard : Up : KeyDown
DELAY : 3750
Keyboard : Left : KeyUp
DELAY : 650
Keyboard : Up : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 9 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 2500
Keyboard : Left : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 8 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 2250
Keyboard : Left : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 7 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 2250
Keyboard : Left : KeyUp
DELAY : 150
Keyboard : Down : KeyDown
DELAY : 650
Keyboard : Down : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 6 : 0 : 0
Keyboard : Up : KeyDown
DELAY : 300
Keyboard : Up : KeyUp
DELAY : 150
Keyboard : Left : KeyDown
DELAY : 2500
Keyboard : Left : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 5 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 100
Keyboard : Down : KeyDown
DELAY : 4000
Keyboard : Right : KeyUp
DELAY : 350
Keyboard : Down : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 4 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 3000
Keyboard : Right : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 3 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 2000
Keyboard : Right : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 2 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 2000
Keyboard : Right : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 1 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 2500
Keyboard : Right : KeyUp
ENDIF
DELAY : 200
INCREMENT CLIPBOARD : 1
GOTO : START-LAB
