REPEAT : 100000 : 0 : 0 : Enter the number of iterations: : 0 : 0
COMMENT : Skinning: F1: regen, F2: WWT, F10: Pois Res F12 MSK
Keyboard : F1 : KeyPress
DELAY : 200
Keyboard : F2 : KeyPress
DELAY : 200
Keyboard : F10 : KeyPress
DELAY : 200
Keyboard : Space : KeyPress
DELAY : 200
REPEAT : 4 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk3WBQAAAAAAADYAAAAoAAAAEgAAABQAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAECEp/xAhKf8QISn/ECEp/xAhKf8QISn/ECEp/xAhKf8QISn/CBgp/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/xAhKf8IGCn/ECEp/xAhKf8QISn/ECEp/wgYKf8IGCH/CBgp/xAhKf8QISn/ECEp/xAhKf8QISn/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgp/xAhKf8QISn/ECEp/wgYIf8IGCH/CBgh/wgYKf8QISn/CBgh/wgYIf8QISn/CBgh/wgYIf8IGCH/CBgh/wAQIf8IGCH/CBgh/wgYIf8IGCn/CBgp/wgYIf8IGCH/OTlr/xgQpf8xIb3/CBgh/wgYIf8IGCn/CBgh/wgYIf8hIZT/c2OM/xAhSv8IGIz/CBgh/wgYIf8YIZT/IRCE/ykYhP8xOVL/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/ABAh/wAQIf8AECH/Qjk5/yEYc/8IGCH/CBgh/wgYIf8IGCH/KSGU/xAhUv8IGCH/CBgh/wgYKf8QISn/ECEp/wgYIf8IGCH/ABAh/wAQGP8AEBj/ABAh/wgYIf8IGCH/MUKU/xAplP8IGHv/GAhK/xAIlP8IEK3/CBil/wgInP8QCKX/nJze/87G7/8hGDn/CBgh/wAQIf8pMVr/CBgh/wgYKf85QoT/ISmt/xgIrf8QCIT/GAhC/xgIlP85Ib3/SjG9/6WU1v8hMZT/GAiE/yEYpf8pKXv/OUK1/xgItf8IEIz/GDla/1pSQv8pMVL/MUKc/xgIpf+9rd7/ITlz/1I5e/8YCJT/1s73/xgQtf+9vef/CBgh/wgYIf8IGCH/CBgh/ykxpf8pOZz/MTlC/xAhKf8QISn/MUJz/yEplP8hGJT/rZTe/xAQe/8YIZz/ITm9/zk5e/85MUL/IRBC/xgIQv8QEHv/MTmM/xAhKf8QISn/ECEp/xAhKf8YEEL/GAg5/zE5e/85Oc7/KTnG/yExtf8YEM7/GBCt/xAIY/8pMVr/KRgp/yEpY/8YCJT/ABAh/wgYIf8IGCn/EBBS/ykxWv8QCFL/CDFS/yk5c/8pMYT/MTm1/yExzv8YKbX/WkKt/2NKvf8QMYz/MSl7/5SExv8hMYT/ABAY/wgYIf8QISn/KTlr/xgYlP8QCIT/GDFa/wgQSv8AECH/CBgh/xAhKf8YEKX/IRB7/yk5pf8xOXP/GCGU/wgYIf8QISn/ABAh/wgYIf8QISn/KTGM/xgQtf+Ea8b/IRB7/wgYKf8IGCH/CBgh/xAhKf8QISn/MTm1/xgQrf8YKaX/CBgh/wgYIf8QISn/CBgh/wgYKf8QISn/CBgh/wgYIf8QISn/ECEp/xAhKf8IGCn/CBgh/wgYKf8QISn/ECEp/xgIQv9CMTn/OTEp/wgYIf8QISn/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgp/wgYKf8IGCn/CBgh/wgYIf8IGCH/CBgp/yEhpf+UhL3/EBBC/wgYKf8IGCn/CBgh/wAQIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8AECH/CBgh/wgYIf8IGCn/ECEp/xAhKf8IGCH/ABAh/wgYIf8IGCH/ECEp/wgYKf8IGCH/CBgh/wAQIf8IGCH/CBgh/wgYIf8AECH/ABAh/wgYIf8IGCn/ECEp/wgYKf8IGCH/ABAh/wgYIf8QISn/ECEp/xAhKf8IGCn/CBgh/wgYIf8IGCn/CBgh/wgYIf8IGCH/CBgp/xAhKf8QISn/CBgh/wgYIf8IGCH/CBgh/xAhKf8QISn/ECEp/xAhKf8QISn/ECEp/wgYKf8IGCH/CBgh/wgYIf8IGCH/ECEp/xAhKf8QISn/CBgh/wgYIf8IGCH/ : 1 : 20 : 0 : 9;47;793;337
DELAY : 100
Keyboard : F12 : KeyPress
DELAY : 150
Mouse : C2 : C1 : Move : 0 : 0 : 0
DELAY : 300
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 3600
ENDIF
IF IMAGE : Qk3WBQAAAAAAADYAAAAoAAAAEgAAABQAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAECEp/xAhKf8QISn/ECEp/xAhKf8QISn/ECEp/xAhKf8QISn/CBgp/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/xAhKf8IGCn/ECEp/xAhKf8QISn/ECEp/wgYKf8IGCH/CBgp/xAhKf8QISn/ECEp/xAhKf8QISn/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgp/xAhKf8QISn/ECEp/wgYIf8IGCH/CBgh/wgYKf8QISn/CBgh/wgYIf8QISn/CBgh/wgYIf8IGCH/CBgh/wAQIf8IGCH/CBgh/wgYIf8IGCn/CBgp/wgYIf8IGCH/OTlr/xgQpf8xIb3/CBgh/wgYIf8IGCn/CBgh/wgYIf8hIZT/c2OM/xAhSv8IGIz/CBgh/wgYIf8YIZT/IRCE/ykYhP8xOVL/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/ABAh/wAQIf8AECH/Qjk5/yEYc/8IGCH/CBgh/wgYIf8IGCH/KSGU/xAhUv8IGCH/CBgh/wgYKf8QISn/ECEp/wgYIf8IGCH/ABAh/wAQGP8AEBj/ABAh/wgYIf8IGCH/MUKU/xAplP8IGHv/GAhK/xAIlP8IEK3/CBil/wgInP8QCKX/nJze/87G7/8hGDn/CBgh/wAQIf8pMVr/CBgh/wgYKf85QoT/ISmt/xgIrf8QCIT/GAhC/xgIlP85Ib3/SjG9/6WU1v8hMZT/GAiE/yEYpf8pKXv/OUK1/xgItf8IEIz/GDla/1pSQv8pMVL/MUKc/xgIpf+9rd7/ITlz/1I5e/8YCJT/1s73/xgQtf+9vef/CBgh/wgYIf8IGCH/CBgh/ykxpf8pOZz/MTlC/xAhKf8QISn/MUJz/yEplP8hGJT/rZTe/xAQe/8YIZz/ITm9/zk5e/85MUL/IRBC/xgIQv8QEHv/MTmM/xAhKf8QISn/ECEp/xAhKf8YEEL/GAg5/zE5e/85Oc7/KTnG/yExtf8YEM7/GBCt/xAIY/8pMVr/KRgp/yEpY/8YCJT/ABAh/wgYIf8IGCn/EBBS/ykxWv8QCFL/CDFS/yk5c/8pMYT/MTm1/yExzv8YKbX/WkKt/2NKvf8QMYz/MSl7/5SExv8hMYT/ABAY/wgYIf8QISn/KTlr/xgYlP8QCIT/GDFa/wgQSv8AECH/CBgh/xAhKf8YEKX/IRB7/yk5pf8xOXP/GCGU/wgYIf8QISn/ABAh/wgYIf8QISn/KTGM/xgQtf+Ea8b/IRB7/wgYKf8IGCH/CBgh/xAhKf8QISn/MTm1/xgQrf8YKaX/CBgh/wgYIf8QISn/CBgh/wgYKf8QISn/CBgh/wgYIf8QISn/ECEp/xAhKf8IGCn/CBgh/wgYKf8QISn/ECEp/xgIQv9CMTn/OTEp/wgYIf8QISn/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgp/wgYKf8IGCn/CBgh/wgYIf8IGCH/CBgp/yEhpf+UhL3/EBBC/wgYKf8IGCn/CBgh/wAQIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8AECH/CBgh/wgYIf8IGCn/ECEp/xAhKf8IGCH/ABAh/wgYIf8IGCH/ECEp/wgYKf8IGCH/CBgh/wAQIf8IGCH/CBgh/wgYIf8AECH/ABAh/wgYIf8IGCn/ECEp/wgYKf8IGCH/ABAh/wgYIf8QISn/ECEp/xAhKf8IGCn/CBgh/wgYIf8IGCn/CBgh/wgYIf8IGCH/CBgp/xAhKf8QISn/CBgh/wgYIf8IGCH/CBgh/xAhKf8QISn/ECEp/xAhKf8QISn/ECEp/wgYKf8IGCH/CBgh/wgYIf8IGCH/ECEp/xAhKf8QISn/CBgh/wgYIf8IGCH/ : 1 : 20 : 0 : 1;269;805;380
DELAY : 100
Keyboard : F12 : KeyPress
DELAY : 300
Mouse : C2 : C1 : Move : 0 : 0 : 0
DELAY : 150
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 3600
ENDIF
ENDREPEAT
ENDREPEAT
