SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
COMMENT : V1 - Based on WWI
COMMENT : --
COMMENT : Log out if kraken found in BP
COMMENT : --
COMMENT : Start bottom left corner
COMMENT : F1=regen, F2=WWT, F3=GFP, F4=Crate, F5=Warr totem
COMMENT : F8=GSP
COMMENT : F12=Lyc potion
LABEL : START-LAB
DELAY : 100
LABEL : Kill Bar - top
Keyboard : F2 : KeyPress
DELAY : 100
Keyboard : F1 : KeyPress
DELAY : 100
REPEAT : 2 : 0 : 0 : Enter the number of iterations: : 0 : 0
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 37;61;765;527
DELAY : 25
Mouse : C24 : C30 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 3500
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 37;58;777;337
COMMENT : Top
DELAY : 25
Mouse : C20 : C28 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 3500
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 37;295;768;343
COMMENT : Btm
DELAY : 50
Mouse : C23 : C30 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 4000
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 37;62;618;520
COMMENT : Wide search
DELAY : 25
Mouse : C25 : C28 : Move : 0 : 0 : 0
DELAY : 25
Mouse : 0 : 0 : LeftButtonDown : 0 : 1 : 0
DELAY : 100
Mouse : 0 : 0 : LeftButtonUp : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 350;254;207;234
COMMENT : Red
DELAY : 50
Mouse : C8 : C35 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk0iDgAAAAAAADYAAAAoAAAAUQAAAAsAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAgI/////////////////wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/////////////////wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP////////////////8AAAj/AAAI/wAICP8ACAj//////wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP////////////////8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP////////////////8AAAj/AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP///////////wAICP8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj//////wAICP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj/AAgI/wAICP//////AAgI/wAICP8ACAj/AAgI//////8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8ACAj/AAgI//////8AAAj//////wAACP8AAAj/AAgI/wAICP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAICP//////AAAI/wAACP//////AAgI/wAICP8AAAj/AAAI/wAACP8AAAj//////wAICP8ACAj//////wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj//////wAICP8ACAj/AAAI/wAACP8AAAD//////wAACP8AAAj//////wAACP8AAAj/AAgI/wAICP8ACAj//////wAICP8ACAj//////wAACP8AAAj/AAAI/wAACP8AAAj//////wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8ACAj/AAgI//////8AAAj//////wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP//////AAgI/wAICP8AAAj/AAAA/wAACP8AAAj//////wAACP8ACAj//////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8ACAj/AAAI/wAACP8AAAj//////wAACP8AAAj//////wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj//////wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj//////wAACP8AAAj/AAgI/wAICP//////AAAI/wAACP8AAAj/AAAI/wAICP//////AAgI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////////////////////////////////////AAAI/wAAAP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8ACAj//////////////////////////////////////wAACP8ACAj//////wAICP8ACAj/AAAI/wAACP8AAAj//////wAACP8AAAj//////wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj//////////////////////////////////////wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj//////wAACP8AAAj/AAAI/wAICP//////AAgI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAD//////wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj//////wAICP8ACAj//////wAICP8ACAj/AAAI/wAACP8AAAj//////wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8ACAj/AAgI/wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj//////wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAgI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj//////wAACP8AAAD/AAAA/wAACP8AAAj//////wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP///////////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP8AAAj//////wAICP8AAAj/AAAI//////8AAAj/AAAI/wAACP///////////wAACP8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAD/AAAA/wAACP//////AAAI/wAACP8AAAj///////////8AAAj/AAAI/wAACP8AAAj//////wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI//////8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP8AAAj/AAAI/wAACP//////AAAI/wAACP//////AAAI/////////////////wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/////////////////wAACP8AAAj/AAAI/wAACP//////AAAI/////////////////wAACP8AAAj//////wAACP8AAAj/AAAI/wAACP////////////////8AAAj/AAAI/wAACP8AAAj//////wAACP//////////////////////AAAI/wAACP8AAAj/AAAI/wAACP////////////////8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP////////////////8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCn/CBgh/wgYIf8IGCn/CBgp/wgYIf8IGCH/CBgh/wgYIf8IGCH/ABAh/wgYIf8IGCH/CBgh/wgYIf8IGCn/CBgp/wgYKf8IGCn/ECEp/wgYKf8IGCH/CBgh/wgYIf8IGCH/ABAh/wgYIf8IGCH/ECEp/xAhKf8QISn/CBgp/wgYIf8IGCH/CBgh/xAhKf8IGCn/CBgh/wgYIf8IGCH/CBgp/wgYKf8IGCn/CBgp/wgYIf8AECH/CBgh/wgYKf8IGCH/CBgh/wgYIf8AEBj/ABAY/wgYIf8IGCH/CBgh/wgYIf8IGCn/ECEp/xAhKf8IGCn/CBgh/wgYIf8IGCH/ABAh/wAQIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYIf8IGCH/CBgh/wgYKf8IGCn/ : 0 : 50 : 0 : 115;781;189;40
COMMENT : Check if still targetting and delay moving off
DELAY : 1500
ENDIF
IF IMAGE : Qk1SAAAAAAAAADYAAAAoAAAABwAAAAEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/w== : 1 : 90 : 0 : 247;173;340;299
COMMENT : Middle + top/btm
DELAY : 50
Mouse : C21 : C25 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C3 : C10 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 3500
ENDIF
LABEL : Finish-Off
IF IMAGE : Qk3SAAAAAAAAADYAAAAoAAAADQAAAAMAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAABAQ/wAQCP8AEAj/ABAI/wAQCP8AEAj/ABAQ/wAQEP8IEBD/CBgQ/xAhGP8IGBD/CBgQ/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8IGBD/CBgQ/wgYGP8IIRj/CCEh/xApIf8QKRj/ECkY/wgYEP8IGBD/CBgQ/wgYGP8IIRj/ : 1 : 90 : 0 : 350;254;207;234
DELAY : 50
Mouse : C13 : C28 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk2GAQAAAAAAADYAAAAoAAAADgAAAAYAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAKWNj/xg5Of8QKTH/CBAQ/yljUv8xa1r/ECEh/xAhKf8IGCH/GEJC/wgYGP8IISH/GEJC/xgxKf8QKSn/IVJa/wgYGP8hUkr/IVJK/xg5Mf8IIRj/AAgI/xAhKf8QISn/ECEh/xAhIf8pWlL/KVpS/wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//IUpK/xgxMf8IIRj/ECkp/wgYGP8IEBD/ECkx/xg5Qv8QISH/EDEx/xApMf8ACBD/ECkp/xg5Mf8QMTH/AAgA/wAICP8QISn/CBAY/xAhIf8hSkr/AAgQ/wAICP8AEBD/EDEx/xhCQv8YOTn/GDkx/wAICP8AAAD/AAgI/xAxMf8IISH/CCEh/xg5Mf8IGBj/ABAQ/wgYGP8AAAD/ECEh/yFKSv8hQkL/ : 1 : 90 : 0 : 301;158;302;293
DELAY : 50
Mouse : C3 : C28 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
ENDIF
IF IMAGE : Qk0WEgAAAAAAADYAAAAoAAAAaAAAAAsAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAICP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAICP8ACAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//9C9///Qvf//0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//0L3//9C9///Qvf//wAICP9C9///AAAA/wAACP9C9///AAAI/wAACP8AAAj/AAgI/0L3//8ACAj/AAgI/wAACP8AAAj/Qvf//wAICP8ACAj/Qvf//wAACP8AAAj/AAAI/wAICP9C9///AAAI/wAACP8AAAj/AAgI/0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//0L3//9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8ACAj/AAAI/wAACP9C9///Qvf//0L3//9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/Qvf//0L3//9C9///AAAI/wAACP8AAAj/AAAI/wAICP9C9///Qvf//0L3//9C9///AAAI/0L3//8ACAj/AAgI/wAICP9C9///AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8ACAj/AAgI/wAICP8ACAj/Qvf//0L3//8AAAj/AAAI/0L3//8ACAj/AAAI/wAACP8ACAj/Qvf//wAICP8ACAj/AAAI/wAACP9C9///AAgI/wAICP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/Qvf//wAICP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAICP8ACAj/AAgI/wAICP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/0L3//8AAAj/AAAI/wAICP8ACAj/AAgI/0L3//8AAAj/AAAI/wAACP9C9///AAgI/wAICP8AAAj/Qvf//wAICP8ACAj/AAgI/wAACP9C9///Qvf//wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAICP8ACAj/AAgI/wAICP8AAAj/Qvf//wAACP8AAAj/Qvf//wAICP8ACAj/AAAI/wAACP9C9///AAgI/wAICP8AAAj/AAAI/0L3//8ACAj/AAgI/0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP9C9///AAAI/wAICP8AAAj/AAAI/wAICP9C9///AAAI/wAACP9C9///AAgI/wAICP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/0L3//8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/0L3//8AAAj/Qvf//wAACP8AAAj/AAgI/wAICP9C9///AAgI/wAACP8AAAj/AAAI/wAICP9C9///AAgI/wAACP9C9///AAgI/wAICP8ACAj/AAAI/wAACP9C9///AAgI/wAICP8ACAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP9C9///AAAI/wAACP9C9///AAAI/wAICP8ACAj/AAAI/wAACP9C9///AAgI/wAICP9C9///AAgI/wAACP8AAAj/AAAI/0L3//8ACAj/AAgI/wAICP8AAAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8AAAj/AAgI/wAICP8ACAj/AAgI/0L3//8ACAj/AAgI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP9C9///AAgI/wAICP9C9///Qvf//wAACP8ACAj/AAgI/0L3//8AAAj/AAAI/wAACP8ACAj/AAgI/0L3//8ACAj/AAAI/0L3//8AAAj/AAgI/wAICP8ACAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/Qvf//0L3//9C9///Qvf//wAICP8ACAj/AAgI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8ACAj/AAgI/0L3//8ACAj/AAAI/wAACP8AAAj/Qvf//wAICP8AAAj/AAAI/wAACP9C9///AAAA/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAICP8ACAj/Qvf//wAACP8AAAj/Qvf//wAICP8ACAj/AAgI/wAICP8ACAj/Qvf//wAICP8ACAj/Qvf//wAICP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/0L3//9C9///Qvf//0L3//8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/0L3//8ACAj/AAgI/wAICP9C9///AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAgI/wAICP8ACAj/Qvf//wAACP8AAAj/Qvf//wAACP8ACAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/0L3//8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/Qvf//wAICP8AAAj/AAAI/wAICP8AAAj/Qvf//wAICP8ACAj/Qvf//wAICP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8ACAj/Qvf//wAICP8ACAj/AAgI/wAICP9C9///AAAI/wAACP9C9///AAgI/wAICP8AAAj/AAgI/wAICP9C9///AAgI/wAICP9C9///AAgI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/Qvf//wAICP8ACAj/AAgI/0L3//8ACAj/AAgI/wAACP9C9///AAgI/wAACP8ACAj/AAgI/wAICP9C9///AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP9C9///AAgI/wAICP8AAAj/AAgI/wAICP9C9///AAgI/wAICP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAD/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAICP8ACAj/AAgI/0L3//8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8ACAj/AAgI/0L3//8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAA/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAICP8ACAj/AAgI/0L3//8ACAj/AAAI/0L3//8ACAj/AAgI/wAICP8ACAj/AAgI/0L3//8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8ACAj/AAgI/0L3//8ACAj/AAgI/wAACP8ACAj/AAgI/0L3//8ACAj/AAgI/0L3//9C9///AAAI/wAACP8AAAj/Qvf//0L3//8AAAj/AAAI/wAACP9C9///AAAI/wAACP9C9///Qvf//wAACP8AAAj/AAAI/0L3//9C9///AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP9C9///AAAI/wAACP8ACAj/Qvf//0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAAA/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAgI/wAICP8ACAj/Qvf//wAICP8AAAj/AAgI/0L3//8ACAj/AAgI/wAICP9C9///AAgI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP9C9///Qvf//0L3//9C9///AAAI/wAACP8ACAj/Qvf//wAICP8ACAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAACP9C9///Qvf//0L3//8AAAj/AAAI/0L3//9C9///Qvf//wAACP8AAAj/AAAI/0L3//8AAAj/Qvf//0L3//9C9///AAAI/wAACP9C9///Qvf//0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//9C9///Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/0L3//9C9///Qvf//0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//0L3//9C9///Qvf//wAACP8AAAj/AAAI/wAAAP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAgI/wAICP9C9///AAgI/wAICP8AAAj/AAAI/0L3//9C9///Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAgI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/w== : 1 : 90 : 0 : 434;945;640;40
COMMENT : Test for summon, do WWT, move right, target
DELAY : 50
Keyboard : Right : KeyDown
DELAY : 220
Keyboard : Right : KeyUp
DELAY : 100
Mouse : 387 : 325 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 100
Mouse : C-3 : C5 : Move : 0 : 0 : 0
DELAY : 100
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 2000
Keyboard : F2 : KeyPress
DELAY : 100
ENDIF
IF IMAGE : Qk0uEAAAAAAAADYAAAAoAAAASQAAAA4AAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8IGBj/EDFC/xhKWv8hWnP/IVpz/xhKWv8QMUL/CBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAQEP8YSlL/MWuE/0qctf+Ezuf/lN7v/5Te7/+Ezuf/UqW9/yljc/8YQlL/AAgQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wgYIf8xa4T/UqW9/2u1xv85Y2v/GCkx/wAAAP8AAAD/ITEx/0pze/+U1uf/SqW1/yFSa/8IEBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wgQEP85hJz/UqW9/0qElP8IGBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/EBgh/3Oltf9rvc7/IVJr/wAIEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8xc4T/SqW1/zFjc/8AAAD/AAAA/wAAAP8AAAj/AABj/wAAUv8AAAD/AAAA/wAAAP8AAAD/Y5Sl/1qtxv8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/UqW9/zl7lP8AAAD/AAAA/wAAAP8AABj/AACU/wAApf8AAJT/AABr/wAACP8AAAD/AAAA/wAICP+U1uf/lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/0qctf8YMUL/AAAA/wAAAP8AABD/AAC1/wAAzv8AAM7/AAC1/wAAnP8AAHP/AAAI/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP85e5T/CBAY/wAAAP8AAAD/AAC1/wAA3v8AAO//AADv/wAA5/8AAL3/AACc/wAAa/8AAAD/AAAA/wAAAP8AAAD/AABr/wAAxv8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/AADn/wAA5/8AAOf/KWuE/wAAAP8AAAD/AABr/wAA7/8AAPf/AAD//wAA//8AAPf/AADn/wAAvf8AAJz/AAAx/wAAAP8AAAD/AAAA/0pK1v+UlO//AADO/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/wAAxv8AAMb/AADG/ylre/8AAAD/AAAA/wAA5/8AAP//AAD//wAA//8AAP//AAD//wAA9/8AAN7/AACt/wAAe/8AAAD/AAAA/wAAAP9KSt7/1tb3/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/+UlO//lJTv/5SU7/8xc4z/ABAQ/wgIIf85Of//ISH//xAQ//8ICP//CAj//wgI//8AAP//AADv/wAAzv8AAKX/AAAI/wAAAP8AAAD/AABr/0pK5/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//Skrv/0pK7/9KSu//QpSt/xApMf8ICCH/c3P//2Nj//9CQv//MTH//zk5//9CQv//OTn//xgY//8AAOf/AADG/wAAEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/3PG1v8hUmv/AAAA/4yMzv+lpf//jIz//3Nz//+EhP//lJT//5SU//9ra///GBj//wAAxv8AAAD/IVJr/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8QMUL/EDFC/xAxQv8= : 0 : 30 : 1 : 813;396;164;244
COMMENT : Test life, pot, clear middle a little more
Keyboard : F3 : KeyPress
DELAY : 250
ENDIF
IF IMAGE : Qk2eDQAAAAAAADYAAAAoAAAAIQAAABoAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wgYGP8QMUL/GEpa/yFac/8hWnP/GEpa/xAxQv8IGBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AEBD/GEpS/zFrhP9KnLX/hM7n/5Te7/+U3u//hM7n/1Klvf8pY3P/ECkx/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wgYIf8xa4T/UqW9/2u1xv85Y2v/GCkx/wAAAP8AAAD/ITEx/0pze/8AAAj/KWNz/xAxOf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/CBAQ/zmEnP9Spb3/SoSU/wgYGP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8pWmv/Spy1/zmMnP8IISn/AAgQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/MXOE/0qltf8AAAD/CCEp/wAACP8AAAD/AAAA/wAAAP8AAAD/AAAA/yFCUv9KlK3/IUJK/ylCSv9CjJz/AAAA/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/AAAA/wAIEP8AAAD/UqW9/wAAAP8YQlL/IVpz/yFSY/8AEBD/AAAA/wAAAP8AAAD/EDE5/0KUpf8pY3P/AAAA/wAICP8AAAD/AAAA/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//AAAA/zFre/8hWmv/ECEp/yFaa/9KnLX/c73O/1Klvf8hWmv/CBgh/xApMf8pa3v/Qoyl/0KUpf8IEBD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/xAQGP9zvc7/Y7XO/1Klvf9Ce4z/CBAQ/3u9zv9Spb3/KWNz/ylaa/9jtc7/Y629/yE5Qv8AAAD/AAAA/wAAAP8AAAD/Wjla/7VanP/eUr3/1kq1/9ZKtf/WSrX/1kq1/9ZKtf/WSrX/1kq1/9ZKtf/WSrX/1kq1/9ZKtf/WSrX/AAAA/wAAAP8YISn/lNbn/0p7jP8AAAD/AAgI/xApKf9zvdb/Qoyl/0KMpf8pUmP/AAAA/wAICP8IEBD/AAAA/wAAAP8AAAD/zpS9/++l3v/GAJz/xgCc/8YAnP/GAJz/xgCc/8YAnP/GAJz/xgCc/8YAnP/GAJz/xgCc/8YAnP/GAJz/AAAA/wAAAP9rtc7/ITE5/wgQEP8IEBj/KWN7/ylSWv97zt7/c8bW/0KMpf8hWnP/CBAY/yFKUv8hWnP/IVpr/xhCUv8AAAD/1pTG//fW7//nlNb/55TW/+eU1v/nlNb/55TW/+eU1v/nlNb/55TW/+eU1v/nlNb/55TW/+eU1v/nlNb/AAAA/wAAAP9jpb3/MXOM/wAAAP8xWmP/Wq3G/xApMf85WmP/jMbe/3vG3v8pa3v/GDFC/0qctf9SjKX/UnuM/3u1xv9ClKX/Y0Ja/9aUxv/nhM7/54TO/+eEzv/nhM7/54TO/+eEzv/nhM7/54TO/+eEzv/nhM7/54TO/+eEzv/nhM7/AAAA/wAAAP9Kc4T/QpSt/xApMf8IEBj/a73O/xg5Sv8AAAD/ITlC/2u91v85e5T/Qoyl/0KUpf8IGCH/AAAA/wgQEP9Kc4T/AAgQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8hMTn/c8bW/yFSa/8AAAD/Qmt7/zmEnP8QKTH/IUpa/0qUrf9KnLX/SpSt/yFKWv8AAAD/AAAA/wAAAP8AAAD/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/IVpz/yFac/8hWnP/AAAA/wAAAP8AAAD/a6Wt/0qctf8YOUr/CAgQ/4TG3v9rvc7/hM7n/5Te7/+U3u//hNbn/yljc/8IGCH/AAgQ/wAAAP9Spb3/a73W/4zW7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//lN7v/5Te7/+U3u//AAAA/wAAAP8AAAD/EBgh/4TO3v85jJz/AAAA/zFKUv85Wlr/ITEx/wgQEP8AAAD/MUpS/3O91v8pY3P/GDlK/wAAAP9KnK3/EBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yExOf+Mzuf/Spy1/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/2Ocpf9zxtb/KWN7/wAQEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8QISH/e629/4zW5/9KnLX/KWN7/yFac/8hWnP/KWt7/yEpMf+c3vf/MWNz/wgQEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yk5Qv9ajJT/e7XG/5Te7/+U3u//a629/1J7jP8IEBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/ : 0 : 30 : 1 : 813;396;164;244
COMMENT : Test if stam out
Keyboard : F8 : KeyPress
DELAY : 250
ENDIF
COMMENT : Check if out of ammo
IF IMAGE : Qk1aGAAAAAAAADYAAAAoAAAAZwAAAA8AAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////3v///97////e////wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///97////e////3v///8ACAj/e////wAACP8AAAj/e////3v///97////AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////e////3v///8AAAj/AAAI/wAICP8AAAj/AAAI/3v///8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/e////wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAD/AAAI/3v///8AAAj/AAgI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAICP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/e////wAACP8AAAj/AAgI/wAICP97////e////3v///8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////3v///8AAAj/AAAA/3v///8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8ACAj/AAAI/wAACP97////AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAD/AAAI/wAACP97////AAgI/wAICP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAgI/3v///8AAAj/AAAI/wAACP97////AAAI/wAAAP8AAAD/e////wAACP8AAAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAgI/wAICP97////AAgI/wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAgI/wAACP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAICP8ACAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAD/AAAI/wAACP97////AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAgI/wAICP8ACAj/e////wAICP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8ACAj/AAgI/wAACP97////AAAI/wAACP97////AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAA/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////3v///97////e////3v///97////e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAICP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAgI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP97////AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAICP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/e////wAICP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8ACAj/AAAI/3v///8AAAj/AAAI/wAACP8ACAj/AAAI/3v///8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAAAP8AAAj/AAAI/wAICP97////AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAAAP97////e////wAACP8AAAj/AAAI/3v///97////AAAI/wAACP8AAAj/e////wAACP8AAAj/e////3v///8AAAj/AAAI/wAACP97////e////wAICP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAAAP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAgI/wAICP97////AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/3v///97////e////3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///97////e////wAACP8AAAj/AAAI/wAACP97////e////3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP97////e////3v///8ACAj/AAgI/3v///97////e////wAACP8AAAj/AAAI/3v///8AAAj/e////3v///97////AAAI/wAICP97////e////3v///8AAAj/AAAI/wAACP8AAAj/AAAI/3v///97////e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/3v///8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/3v///8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/e////wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/e////wAACP8AAAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP97////AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP97////AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP97////e////3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP97////AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/3v///97////AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/3v///8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAD/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/ : 0 : 30 : 0 : 333;875;771;102
PLAY MACRO : C:\Macros\logout.mcr
DELAY : 28842000
ENDIF
IF IMAGE : Qk1GAwAAAAAAADYAAAAoAAAADgAAAA4AAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAShAA/1IIAP9jCAD/OUoA/5QAAP+lAAD/tQAA/6UAAP+ECAD/WhAA/3sYAP+lMQD/lDkA/5Q5CP8YAAD/GAAA/xgAAP9jGAD/AAAA/6UAAP8AAAD/9yEA/0IAAP+lAAD/QgAA/5QYAP+cMQD/lDkA/1IIAP9rAAD/ewAA/zEhAP8AAAD/3gAA//8AAP/GYwD/zhgA/9YAAP85AAD/rRgA/6UxAP+UMQD/WhAA/2sAAP+EAAD/KQAA/wAAAP//AAD//0IA/1qlAP/GSgD/AAAA//cIAP/GEAD/pTEA/5QxAP8YEAD/KQAA/4QAAP+EAAD/MRAA/3MAAP//GAD//1oA/zEAAP/eAAD/tQAA/70YCP+cMRD/lDkY/3MIAP9rAAD/cwAA/4QAAP/OAAD/IQAA/6UhAP+lIQD/QmMA/9YAAP/eCAD/tSEI/5Q5GP+MQin/ewAA/4QAAP9zAAD/ewAA/70AAP/nAAD/5wAA/+cAAP/nAAD/5wAA/84QAP+tKQD/nDEA/5Q5EP9zAAD/ewAA/3sAAP+EAAD/xgAA/+cAAP/nAAD/5wAA/+cAAP/eAAD/vRgA/6UpAP+lKQD/rSkA/ykAAP9zAAD/ewAA/4wAAP/WAAD/5wAA/+cAAP/nAAD/5wAA/84QAP+9IQD/tSEA/8YYAP/OEAD/QmMA/4wAAP8xAAD/jAAA/9YAAP/nAAD/5wAA/+cAAP/eAAD/zhAA/84QAP/WCAD/3gAA/+cAAP97AAD/ewAA/3sAAP+MAAD/1gAA/+cAAP/nAAD/5wAA/+cAAP/eAAD/3gAA/+cAAP/nAAD/5wAA/3MAAP9zAAD/MQAA/5QAAP/nAAD/5wAA/+cAAP/nAAD/5wAA/+cAAP/nAAD/5wAA/+cAAP/nAAD/KQAA/3MAAP97AAD/lAAA/ykAAP+lAAD/5wAA/+cAAP/nAAD/5wAA/+cAAP8hAAD/zgAA/9YIAP9rCBD/cwAA/3sAAP+EAAD/AAAA/0IAAP+9AAD/5wAA/+cAAP/nAAD/c1IA/wAAAP9CIQD/tSEA/w== : 0 : 30 : 0 : 1119;779;148;186
COMMENT : Test for kraken drop
PLAY MACRO : C:\Macros\logout.mcr
DELAY : 28842000
ENDIF
PLAY MACRO : C:\Macros\Hunting\test-dead.mcr
ENDREPEAT
LABEL : Test for movement
IF CLIPBOARD EQUALS : 15 : 0 : 0
COMMENT : Restart circuit and do stuff that happens once a loop
Keyboard : F4 : KeyPress
DELAY : 100
Keyboard : F5 : KeyPress
DELAY : 125
IF IMAGE : Qk0KGwAAAAAAADYAAAAoAAAAZQAAABEAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAAAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAICP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/0L3//9C9///Qvf//0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP9C9///Qvf//0L3//8ACAj/AAgI/wAICP8ACAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/Qvf//0L3//9C9///Qvf//wAACP9C9///AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//9C9///Qvf//0L3//8ACAj/Qvf//wAACP8AAAj/AAAI/wAACP9C9///Qvf//0L3//8AAAj/Qvf//wAACP8AAAj/AAAI/0L3//9C9///Qvf//0L3//8AAAj/Qvf//wAACP8AAAD/Qvf//wAICP8ACAj/Qvf//wAICP8ACAj/AAgI/wAICP8AAAj/Qvf//wAAAP8AAAj/AAAI/0L3//8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAgI/wAICP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/Qvf//wAACP8ACAj/AAgI/0L3//8ACAj/AAgI/wAICP9C9///AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//0L3//8AAAj/AAAI/0L3//8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAgI/0L3//9C9///AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/0L3//9C9///AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//9C9///AAAI/wAAAP9C9///AAgI/wAICP9C9///AAgI/wAICP8ACAj/AAgI/wAICP9C9///AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8ACAj/AAgI/0L3//8ACAj/AAgI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAAAP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8ACAj/AAgI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8ACAj/AAgI/wAICP8ACAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP9C9///AAAI/wAICP8AAAj/AAAI/wAACP9C9///AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAICP8ACAj/Qvf//wAICP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAICP8ACAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAgI/wAICP9C9///AAgI/wAACP9C9///AAAI/wAICP8AAAj/AAAI/wAACP9C9///AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP9C9///Qvf//0L3//8ACAj/AAgI/0L3//8AAAj/AAAI/0L3//8AAAD/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/Qvf//0L3//9C9///AAAI/wAACP9C9///AAgI/wAICP9C9///AAgI/wAICP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/Qvf//0L3//9C9///AAgI/wAICP9C9///AAAI/wAACP9C9///AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAICP8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8ACAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8ACAj/AAgI/wAACP8AAAj/AAgI/wAICP9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//9C9///Qvf//wAACP8AAAD/Qvf//wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP9C9///Qvf//0L3//8ACAj/AAgI/0L3//8ACAj/AAgI/wAICP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP9C9///Qvf//0L3//8ACAj/AAgI/0L3//8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAgI/0L3//8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8ACAj/AAgI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAICP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/Qvf//wAICP8ACAj/AAAI/wAACP8ACAj/AAgI/0L3//8AAAj/AAAA/wAACP8AAAj/Qvf//wAICP8ACAj/AAgI/wAACP9C9///AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAICP9C9///AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAICP8ACAj/AAAI/wAACP8ACAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAgI/wAICP8ACAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8ACAj/Qvf//wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8ACAj/Qvf//wAICP8AAAj/AAAI/wAICP8ACAj/AAAI/wAACP8ACAj/AAAI/wAACP9C9///Qvf//wAAAP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP9C9///Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//0L3//8AAAj/AAAI/wAACP9C9///Qvf//wAICP8ACAj/AAgI/0L3//8AAAj/AAAI/wAACP9C9///AAAI/wAACP8ACAj/AAgI/0L3//8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/0L3//9C9///AAAI/wAACP8AAAD/Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP9C9///AAAI/wAACP9C9///Qvf//wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/Qvf//0L3//9C9///Qvf//wAICP8ACAj/AAgI/wAACP8AAAj/Qvf//0L3//9C9///AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/Qvf//0L3//9C9///AAAI/wAACP9C9///AAAI/0L3//9C9///Qvf//wAACP8AAAj/Qvf//0L3//9C9///AAgI/wAACP8AAAj/AAAI/wAACP9C9///Qvf//0L3//9C9///AAgI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/Qvf//0L3//9C9///Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//0L3//9C9///AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/Qvf//0L3//9C9///Qvf//wAICP8AAAj/AAAI/0L3//8AAAj/AAAI/0L3//8AAAj/Qvf//0L3//9C9///Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP9C9///AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8ACAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAICP8ACAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAgI/wAICP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/Qvf//wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8ACAj/AAAI/wAACP8AAAj/AAAI/0L3//8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAD/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAA/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAACP8AAAj/AAAI/wAAAP8AAAj/AAAI/wAACP8AAAj/AAAI/w== : 0 : 30 : 0 : 46;713;203;99
DELAY : 10020
ENDIF
SET CLIPBOARD : 1 : 0 : Please enter the text to store in clipboard:
ENDIF
IF CLIPBOARD EQUALS : 13 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 3000
Keyboard : Down : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 12 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 2500
Keyboard : Down : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 11 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 2500
Keyboard : Down : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 10 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 3000
Keyboard : Up : KeyDown
DELAY : 1500
Keyboard : Up : KeyUp
DELAY : 200
Keyboard : Left : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 9 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 200
Keyboard : Left : KeyDown
DELAY : 1000
Keyboard : Down : KeyUp
DELAY : 200
Keyboard : Left : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 8 : 0 : 0
Keyboard : Down : KeyDown
DELAY : 1000
Keyboard : Down : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 7 : 0 : 0
Keyboard : Left : KeyDown
DELAY : 1000
Keyboard : Left : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 6 : 0 : 0
Keyboard : Up : KeyDown
DELAY : 3500
Keyboard : Up : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 5 : 0 : 0
Keyboard : Up : KeyDown
DELAY : 3250
Keyboard : Up : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 4 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 2000
Keyboard : Right : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 3 : 0 : 0
Keyboard : Up : KeyDown
DELAY : 1750
Keyboard : Up : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 2 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 2250
Keyboard : Right : KeyUp
ENDIF
IF CLIPBOARD EQUALS : 1 : 0 : 0
Keyboard : Right : KeyDown
DELAY : 2500
Keyboard : Right : KeyUp
ENDIF
DELAY : 250
INCREMENT CLIPBOARD : 1
Mouse : 811 : 351 : Move : 0 : 0 : 0
DELAY : 100
GOTO : START-LAB
