IF IMAGE : Qk0+AQAAAAAAADYAAAAoAAAACwAAAAYAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAMSEA/zEhAP8xIQD/MSEA/zEhAP8pIQj/KSkQ/ykhAP8xIQD/MSEA/zEhAP8xKQD/MSEA/zEhAP8xIQD/KSEI/ykpEP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEpAP8xKQD/MSEA/ykpEP8pIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8pKQj/KSEA/zEhAP8xGAD/MRgA/zEYAP8xGAD/MRgA/zEYAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xIQD/MSEA/zEhAP8xGAD/MRgA/zEYAP8xIQD/ : 1 : 45 : 0 : 251;161;362;362
Keyboard : A : KeyPress
DELAY : 110
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 110
Keyboard : A : KeyPress
DELAY : 70
ENDIF
IF IMAGE : Qk3SAwAAAAAAADYAAAAoAAAAFQAAAAsAAAABACAAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAGBAA/xgIAP8YCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/GBAA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xgIAP8YCAD/GAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8YCAD/IRAA/xgQAP8YCAD/GAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xgIAP8YCAD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//IRAA/xgQAP8YCAD/GBAA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xAIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xAIAP8YCAD/GAgA/xgIAP8YCAD/GBAA/xgQAP8YCAD/GBAA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8QCAD/EAgA/xAIAP8QCAD/EAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/IQgA/xgQAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/IQgA/xgIAP8YEAD/GAgA/xgQAP8YCAD/GAgA/xAIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/IQgA/xgQAP8hEAD/GBAA/xgQAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/GAgA/xgIAP8YCAD/ : 1 : 30 : 0 : 244;131;341;336
Keyboard : A : KeyPress
DELAY : 110
Mouse : 0 : 0 : Click : 0 : 1 : 0
DELAY : 110
Keyboard : A : KeyPress
DELAY : 70
ENDIF
